import { Translations } from './types';

export const en: Translations = {
  common: {
    save: 'Save',
    edit: 'Edit',
    cancel: 'Cancel',
    done: 'Done',
    loading: 'Loading...',
    next: 'Next',
    back: 'Back',
    delete: 'Delete',
    clear: 'Clear',
    confirm: 'Confirm',
    copied: 'Copied!',
    cancelled: 'Cancelled',
    pickup: 'Pickup',
    dropoff: 'Drop-off',
    stop: 'Stop {number}',
    vehicle: 'Vehicle',
    pricing: 'Pricing',
    preferences: 'Preferences',
    date: 'Date',
    time: 'Time',
    seat: 'seat',
    seats: 'seats',
    shareLiveLocation: 'Share Live Location',
    today: 'Today',
    openingMap: 'Opening Map',
    navigatingTo: 'Navigating to',
    addressCopied: 'Address Copied',
    success: 'Success',
    error: 'Error',
  },
  login: {
    brandName: 'ZyncRide',
    brandTagline: 'Travel together. Save together.',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '1234567890',
    phoneError: 'Please enter a valid phone number',
    getOtp: 'Get OTP',
    otpInfoBox:
      'By continuing, you agree to the Terms of Service and Privacy Policy of ZyncRide.',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    orContinueWith: 'OR CONTINUE WITH',
    truecallerPrefix: 'Or, Login with ',
    truecallerSuffix: 'truecaller',
    truecallerErrorTitle: 'Truecaller Error',
    truecallerInitFailed: 'Failed to initialize Truecaller.',
    truecallerLoginFailed: 'Failed to login with Truecaller.',
    truecallerUnavailableTitle: 'Truecaller Unavailable',
    truecallerUnavailableMessage:
      'Truecaller app is not installed or configured on this device.',
    truecallerStartError: 'Could not start Truecaller login',
    truecallerInvalidCredentials:
      'Invalid credentials received from Truecaller',
    continueButton: 'Continue',
    orDivider: 'or',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    termsPrefix: 'By continuing, you agree to the ',
    termsAnd: ' and ',
    termsSuffix: ' of ZyncRide.',
    needHelp: 'Need Help?',
    english: 'English',
    hindi: 'हिंदी',
    trustVerified: 'Verified profiles',
    trustSecure: 'Secure OTP login',
    trustCommunity: 'Community-powered rides',
  },
  otpVerification: {
    titlePrefix: "Confirm it's",
    titleHighlight: 'you',
    screenName: 'OTP Verification',
    subtitle:
      "We've sent a 6-digit verification code to your registered mobile number:",
    verifyButton: 'Verify Identity',
    verifyingButton: 'Verifying...',
    didNotReceive: "Didn't receive the code?",
    resendNow: 'Resend code now',
    resendIn: 'Resend code in',
    secureAuth: 'Secure Verification',
    needHelp: 'Need help? Chat with Sarah',
    privacyPolicy: 'Privacy Policy',
    supportCenter: 'Support Center',
  },
  profileSetup: {
    headerTitle: 'Verdant Trust',
    heroTitle: 'Welcome home.',
    heroSubtitle:
      "Let's curate your digital identity to tailor your experience.",
    dobRequiredError: 'Please provide your legal Date of Birth to proceed.',
    requiredFieldsError: 'Please fill all mandatory fields to continue.',
    identityProfile: 'Identity Profile',
    publicPresence: 'Public Presence',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'E.g. Julianne Reed',
    dobLabel: 'Date of Birth',
    genderLabel: 'Gender',
    genderFemale: 'Female',
    genderMale: 'Male',
    genderOther: 'Other',
    locationPreference: 'Location Preference',
    locationPlaceholder: 'Search your city...',
    nearbyOnly: 'Nearby Only',
    globalReach: 'Global Reach',
    newsletter: 'Newsletter',
    personalizedSuggestions: 'Personalized Suggestions',
    contentPreferences: 'Content Preferences',
    interestDigitalArt: 'Digital Art',
    interestSustainableLiving: 'Sustainable Living',
    interestMinimalism: 'Minimalism',
    interestTypography: 'Typography',
    interestTechEthics: 'Tech Ethics',
    interestArchitecture: 'Architecture',
    almostThere: 'Almost there!',
    identityVerified: 'Your core identity details are verified and secure.',
    completeSetup: 'Complete Setup',
    addPhoto: 'Add Photo',
    under18Error: 'You must be at least 18 years old.',
    footerVersion: 'Secure Editorial Environment • v1.0.2',
  },
  profileHub: {
    headerTitle: 'Profile',
    identityVerified: 'Identity Verified',
    proPooler: 'Pro Pooler',
    rating: 'Rating',
    rides: 'Rides',
    memberSince: 'Member Since',
    trustScore: 'Trust Score',
    trustScoreDescr:
      'Your consistency makes the community safer and more reliable for everyone.',
    accountManagement: 'Account Management',
    supportLegal: 'Support & Legal',
    chooseFromGallery: 'Choose from Gallery',
    removePhoto: 'Remove Photo',
    editProfile: 'Edit Profile',
    editProfileDescr: 'Name, Bio, and Contact details',
    editProfilePic: 'Edit',
    identityVerification: 'Identity Verification',
    identityVerificationDescr: 'Aadhaar & Vehicle Documentation',
    travelPreferences: 'Travel Preferences',
    travelPreferencesDescr: 'Music, smoking, and pet choices',
    paymentMethods: 'Payment Methods',
    paymentMethodsDescr: 'Wallets, Cards, and UPI',
    ratingsReviews: 'Ratings & Reviews',
    ratingsReviewsDescr: 'Check what others are saying',
    changePassword: 'Change Password',
    changePasswordDescr: 'Security and authentication',
    helpSupport: 'Help & Support',
    aboutUs: 'About Us',
    termsPrivacy: 'Terms & Privacy',
    logout: 'Logout',
    deleteAccount: 'Delete Account',
    navBook: 'BOOK',
    navPublish: 'PUBLISH',
    navMyRides: 'MY RIDES',
    navChats: 'CHATS',
    navProfile: 'PROFILE',
    suggestionsFeedback: 'Suggestions & Feedback',
    suggestionsFeedbackDescr: 'Suggest new features or report issues',
  },
  editProfile: {
    headerTitle: 'Edit Profile',
    successMessage: 'Profile updated successfully',
    updatePhoto: 'Update Photo',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'Enter your full name',
    emailLabel: 'Email Address',
    emailPlaceholder: 'Enter your email',
    phoneLabel: 'Phone Number',
    phonePlaceholder: 'Enter your phone number',
    dobLabel: 'Date of Birth',
    genderLabel: 'Gender',
    bioLabel: 'Bio',
    bioPlaceholder: 'Tell us a bit about yourself',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    fullNameRequired: 'Full name is required',
    fullNameMin: 'Name must be at least 3 characters',
    emailRequired: 'Email is required',
    emailInvalid: 'Please enter a valid email',
    phoneRequired: 'Phone number is required',
    phoneInvalid: 'Please enter a valid phone number',
    dobRequired: 'Date of birth is required',
    genderRequired: 'Gender is required',
    bioMax: 'Bio cannot exceed 150 characters',
  },
  dummyContent: {
    aboutTitle: 'About Us',
    aboutBody:
      'RidePoolCompany is dedicated to connecting travelers in a safe and efficient manner.\n\nFounded in 2024, our mission is to reduce carbon emissions and build a community-driven travel network. We prioritize safety, verified profiles, and seamless coordination.',
    helpTitle: 'Help Center',
    helpBody:
      'Common Questions:\n\nQ: How do I book a ride?\nA: Search for your destination, select a verified host, and request a seat.\n\nQ: Is my data secure?\nA: Yes, we use enterprise-grade encryption to protect your identity.\n\nQ: Can I cancel my booking?\nA: Yes, you can cancel up to 2 hours before departure without penalties.',
    termsTitle: 'Terms & Conditions',
    termsBody:
      'Welcome to RidePoolCompany.\n\n1. Acceptance of Terms\nBy accessing and using our application, you accept and agree to be bound by the terms and provision of this agreement.\n\n2. User Responsibilities\nUsers must provide accurate information and maintain the security of their accounts.\n\n3. Code of Conduct\nAny abusive, fraudulent, or illegal activity will result in immediate termination of the account.\n\n4. Limitation of Liability\nRidePoolCompany is not liable for any indirect damages arising from the use of our service.',
    emailUs: 'Email Support',
  },
  travelPreferences: {
    headerTitle: 'Travel Preferences',
    heroTitle: 'Shape your journey.',
    heroSubtitle: 'Let co-riders know what you prefer.',
    nonSmoking: 'Non-smoking',
    nonSmokingDescr: 'No smoking during the ride',
    womenOnly: 'Women only',
    womenOnlyDescr: 'Prefer female co-riders',
    musicPreference: 'Music Preference',
    bollywood: 'Bollywood',
    pop: 'Pop',
    jazz: 'Jazz',
    podcast: 'Podcast',
    silence: 'Silence',
    any: 'Any',
    luggageAllowed: 'Luggage allowed',
    petFriendly: 'Pet friendly',
    manualApproval: 'Instant Approval',
    manualApprovalDescr: 'Bookings are confirmed instantly',
    waitingTime: 'Waiting Time',
    waitingTimeDescr: 'Max time Host waits at pickup',
    savePreferences: 'Save Preferences',
    enabled: 'Enabled',
    disabled: 'Disabled',
  },
  vehicleDetails: {
    headerTitle: 'Vehicle Details',
    heroTitle: 'Register your ride.',
    heroSubtitle: 'Add vehicle details for verification and identification.',
    basicIdentity: 'Basic Identity',
    vehicleCompany: 'Vehicle Company',
    companyPlaceholder: 'E.g. Hyundai',
    carModel: 'Car Model',
    modelPlaceholder: 'E.g. i20',
    technicalSpecs: 'Technical Specs',
    numberPlate: 'Number Plate',
    platePlaceholder: 'E.g. DL 01 AB 1234',
    vehicleType: 'Vehicle Type',
    appearance: 'Appearance',
    manufacturingYear: 'Manufacturing Year',
    color: 'Color',
    colorPlaceholder: 'E.g. White',
    saveVehicle: 'Save Vehicle',
    successMessage: 'Vehicle saved successfully',
    sedan: 'Sedan',
    suv: 'SUV',
    hatchback: 'Hatchback',
    bike: 'Bike',
    capacity: 'Capacity',
    seaterCount: 'Number of Seats',
    seater5: '5 Seater',
    seater7: '7 Seater',
    deleteVehicleTitle: 'Delete Vehicle',
    deleteVehicleConfirmMsg:
      'Are you sure you want to remove this vehicle? This action cannot be undone.',
  },
  chat: {
    headerTitle: 'Chats',
    searchPlaceholder: 'Search contacts or messages...',
    recentMessages: 'Recent Messages',
    noMessages: 'No messages yet',
    newMessage: 'New Message',
    rideLabel: 'Ride',
    yesterday: 'Yesterday',
    activeDrivers: 'Active Ride Hosts',
    safetmsg:
      'NEVER SHARE YOUR PHONE NUMBER OR PERSONAL DETAILS IN CHAT. KEEP CONVERSATIONS WITHIN THE APP FOR YOUR SAFETY.',
    emptyTitle: 'No conversations yet',
    emptyDescription:
      'Start a conversation with your co-riders to coordinate your journey.',
    locationShared: '📍 Location shared',
    sendFailedTitle: 'Message Failed',
    sendFailedMessage: 'Cannot send message please try again',
    connecting: 'Connecting...',
    offline: 'Offline',
    tapToReconnect: 'Tap to reconnect',
  },
  rideDetails: {
    headerTitle: 'Ride Details',
    cancellationReasonTitle: 'Cancellation Reason',
    timelineTitle: 'Journey Itinerary',
    fetchingDetails: 'Curating ride details for you...',
    liveTracking: 'Live Tracking',
    pickupLabel: 'Pickup',
    stopLabel: 'Stop',
    destinationLabel: 'Destination',
    estimatedArrival: 'Est. Arrival',
    minsAway: 'mins away',
    totalFare: 'Total Fare',
    verified: 'Verified',
    otherRiders: 'Other Riders',
    spotsLeft: 'spots left',
    coRider: 'Co-rider',
    joiningAt: 'joining at',
    trustTitle: 'Trusted Ride',
    trustDescription: 'Verified Ride Host and safe community.',
    cancelRide: 'Cancel Ride',
    cancelBooking: 'Cancel My Booking',
    selectSeat: 'Select a Seat',
    chat: 'Chat',
    myRide: 'My Ride',
    groupChat: 'Group Chat',
    ridesLabel: 'rides',
    bookingTotal: 'Booking Total',
    seatsLabel: 'Seats',
    seatLabel: 'seat(s)',
    paymentLabel: 'Payment',
    cashLabel: 'Cash',
    passengers: 'Co-travelers',
    driver: 'Ride Host',
    seatsLeft: '{count} seats left',
    journeyComfort: 'JOURNEY COMFORT',
    journeyItinerary: 'JOURNEY ITINERARY',
    yourFare: 'YOUR FARE',
    perSeatNote: 'per seat · no hidden fees',
    smokeFree: 'Smoke-Free Ride',
    petsWelcome: 'Pets Welcome',
    luggageOk: 'Luggage OK',
    ladiesOnly: 'Ladies Only',
    approvalRequired: 'Approval Required',
    instantBooking: 'Instant Booking',
    vibes: 'Vibes',
    date: 'Date',
    time: 'Time',
    duration: 'Duration',
    seatsLeftLabel: 'Seats Left',
    assignedVehicle: 'ASSIGNED VEHICLE',
    compactSedan: 'Compact Sedan',
    premiumSuv: 'Premium SUV',
    swiftBike: 'Swift Bike',
    standardVehicle: 'Standard',
    passengerDetailsTitle: 'Passenger Details',
    fellowTravelersTitle: 'Your Fellow Travelers',
    noPassengersBooked: 'No passengers have booked yet.',
    noCoRidersYet: 'No co-riders yet. Be the first one to give company!',
    seatLabelSingular: 'Seat',
    seatsLabelPlural: 'Seats',
    reportSuccessTitle: 'Report Submitted',
    reportSuccessMessage:
      'Thank you. Our Safety Excellence Team is investigating the incident.',
  },
  cancelRide: {
    title: 'Cancel Ride',
    subtitle: 'Please select a reason for cancelling',
    reasonDriverFar: 'Host is too far',
    reasonChangedMind: 'Changed my mind',
    reasonCheaperRide: 'Found cheaper ride',
    reasonWaitLong: 'Wait time is too long',
    reasonPlansChanged: 'Plans changed',
    reasonAlternative: 'Found another ride',
    reasonUncomfortable: 'Not comfortable with pickup point',
    reasonNotAvailable: 'Vehicle not available',
    reasonOther: 'Other',
    successMessage: 'Cancellation successful.',
    errorMessage: 'Cancellation failed.',
    confirmCancel: 'Confirm Cancellation',
    keepRide: 'Keep Ride',
    otherReasonPlaceholder: 'Please specify...',
  },
  locationSelection: {
    titlePrefix: 'Where to',
    titleHighlight: 'go',
    titleSuffix: 'next?',
    subtitle: 'Select locations to start your journey.',
    startLabel: 'From where?',
    startPlaceholder: 'Search pickup location...',
    destinationLabel: 'To where?',
    destinationPlaceholder: 'Search destination...',
    continueJourney: 'Continue Journey',
    contextualInfo: 'Ride with verified partners.',
    recentRidesTitle: 'Recent Rides',
  },
  mapPicker: {
    title: 'Select Location',
    searchPlaceholder: 'Search location...',
    setPickup: 'Set Pickup',
    setDestination: 'Set Destination',
    setStop: 'Set Stop',
    selectedArea: 'Selected Area',
    selectLocation: 'Select Location',
    recentSearches: 'Recent Searches',
    locating: 'Locating...',
    pleaseWait: 'Please wait...',
  },
  routeSelection: {
    headerTitle: 'Select Route',
    stepIndicator: 'Step 1/6',
    title: 'Choose best route',
    subtitle: 'Select the route that fits you best.',
    recommended: 'Recommended',
    trustBadge: 'Verdant Trust Verified',
    continue: 'Continue',
  },
  middleStops: {
    headerTitle: 'Middle Stops',
    stepIndicator: 'Step 2/6',
    title: 'Add stops',
    subtitle: 'Add pickup or drop-off stops along the way.',
    startPointLabel: 'Start Point',
    stopLabel: 'Stop',
    addMiddleStop: 'Add Middle Stop',
    addMiddleStopSub: 'Choose location along the route',
    destinationLabel: 'Destination',
    optimizedRoute: 'Optimized Route',
    continue: 'Continue',
    duplicateStopTitle: 'Duplicate Stop',
    duplicateStopMsg: 'This stop is already included in your route.',
  },
  middleStopMap: {
    headerTitle: 'Add Stop',
    stepIndicator: 'Step 2/6',
    searchPlaceholder: 'Search stop location...',
    whereWillYouStop: 'Where will you stop?',
    addingStopsIncreasesInfo:
      'Adding stops increases chances of finding more riders.',
    suggestedStoppages: 'Suggested Stops',
    popular: 'Popular',
    quickExit: 'Quick Exit',
    recentHistory: 'Recent History',
    currentRoute: 'Current Route',
    selectedStop: 'Selected Stop',
    addedStops: 'Added Stops',
    continue: 'Continue',
    distanceFromRoute: '{{distance}} km from route',
    tooFarFromRoute: 'Too far from your route',
    tooFarFromRouteMsg:
      'This stop is more than 1 km from your selected route. Please choose a closer location.',
    selectOnMap: 'Or select on the map',
    confirmStop: 'Confirm Stop',
  },
  dateSelection: {
    headerTitle: 'Select Date',
    stepIndicator: 'Step 3/6',
    title: 'Travel Date',
    subtitle: 'When are you planning to travel?',
    currentLabel: 'Current',
    daysOfWeek: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    selectedDate: 'Selected Date',
    noneSelected: 'None',
    next: 'Next',
  },
  timeSelection: {
    headerTitle: 'Select Time',
    stepIndicator: 'Step 4/6',
    title: 'Time of',
    titleHighlight: 'Departure',
    subtitle: 'Set departure time for accurate pickup.',
    selectedTimeLabel: 'Selected Time',
    formatLabel: 'Time Format',
    arrivalNote: 'Arrival time may vary based on traffic.',
    continue: 'Continue',
  },
  seatSelection: {
    headerTitle: 'Select Seats',
    title: 'Number of seats',
    subtitle: 'How many seats are available?',
    seatSelected: 'seat selected',
    seatsSelected: 'seats selected',
    selectVehicleFirst:
      'Please select a vehicle to view the seating arrangement.',
    yourVehicles: 'Your Vehicles',
    fiveSeater: '5 Seater',
    sevenSeater: '7 Seater',
    driverLabel: 'Host',
    legendSelected: 'Selected',
    legendAvailable: 'Available',
    legendOccupied: 'Occupied',
    seatsOffering: 'Offering seats',
    estEarnings: 'Est. Earnings',
    continue: 'Continue',
  },
  priceSelection: {
    headerTitle: 'Pricing',
    title: 'Set Price',
    subtitle: 'Determine the fare per seat.',
    basePriceLabel: 'Base Price',
    recommendedBadge: 'Recommended',
    frontSeatPremiumTitle: 'Front Seat Premium',
    frontSeatPremiumDesc: 'Extra charge for the front seat',
    premiumAmountLabel: 'Premium Amount',
    maxLimitNote: 'Max limit applied',
    multiStopTitle: 'Multi-stop Pricing',
    multiStopSubtitle: 'Customize prices for different stops',
    customizePricing: 'Customize Pricing',
    continueButton: 'Continue',
    segmentSheetTitle: 'Segment Pricing',
    segmentSheetSubtitle: 'Set prices for each stop',
    segmentLabel: 'Segment',
    minPriceLabel: 'Min',
    maxPriceLabel: 'Max',
    cancelButton: 'Cancel',
    saveButton: 'Save',
    frontSeatProjectedLabel: 'Front Seat Projected',
    perSeatPrice: 'Per Seat Price',
    basePlusPremium: 'Base + {percentage}% premium calculated for this leg',
  },
  requestType: {
    headerTitle: 'Request Type',
    title: 'Choose booking type',
    subtitle: 'How can co-travelers book your ride?',
    instantBookingTitle: 'Instant Booking',
    instantBookingSubtitle: 'Accept requests automatically',
    requestReviewTitle: 'Request Review',
    requestReviewSubtitle: 'Accept each request manually',
    proTipTitle: 'Pro Tip',
    proTipText:
      'Instant booking increases chances of filling your ride quickly.',
    continueButton: 'Continue',
  },
  summaryPublish: {
    headerTitle: 'Summary',
    title: 'Publish Ride',
    subtitle: 'Review your ride details before publishing.',
    departureLabel: 'Departure',
    arrivalLabel: 'Arrival',
    vehicleLabel: 'Vehicle',
    availabilityLabel: 'Availability',
    ridePreferencesLabel: 'Ride Preferences',
    noSmoking: 'No Smoking',
    petsAllowed: 'Pets Allowed',
    chillMusic: 'Chill Music',
    publishRideButton: 'Publish Ride',
    termsText1: 'By publishing, you agree to our ',
    termsLink: 'Community Guidelines',
    termsText2: ' and Safety Terms.',
    routeSummaryLabel: 'Route Summary',
    departureScheduleLabel: 'Departure Schedule',
    addVehicleLabel: 'Add Vehicle',
    addPreferencesLabel: 'Add Preferences',
    approvalRequired: 'Approval Required',
    instantBooking: 'Instant Booking',
  },
  publishSuccess: {
    headerTitle: 'Success',
    title: 'Ride Published!',
    subtitle: 'Your ride is now available for co-travelers.',
    infoTitle: 'Next Steps',
    infoText: 'Keep an eye on co-traveler booking requests and chat with them.',
    primaryCTA: 'Go to My Rides',
    secondaryCTA: 'Share Details',
  },
  bookRideInfo: {
    heroTitle: 'Find a Ride',
    heroSubtitle: 'Travel with verified community partners.',
    pickupLabel: 'Pickup',
    pickupPlaceholder: 'Enter pickup location',
    destinationLabel: 'Destination',
    destinationPlaceholder: 'Enter destination',
    travelDateLabel: 'Travel Date',
    datePlaceholder: 'Today',
    peopleCountLabel: 'Number of people',
    peopleCountSub: 'Including you',
    searchButton: 'Search Rides',
    recentSearchesTitle: 'Recent Searches',
    clearAll: 'Clear All',
    trustTitle: 'Verdant Trust',
    trustDescription: 'Experience safe and reliable travel.',
    brandName: 'ZyncRide',
    local: 'Local',
    intercity: 'Intercity',
    localServiceArea: 'Local Service Area',
    requestLocalPartner: 'Request Local Partner',
  },
  availableRides: {
    heroTitle: 'Available Rides',
    heroSubtitle: 'Choose the best option for your journey.',
    timeFilterLabel: 'Time',
    noSmokingFilterLabel: 'No Smoking',
    ladiesOnlyFilterLabel: 'Ladies Only',
    topRatedFilterLabel: 'Top Rated',
    frequentCoRiderBadge: 'Frequent Co-rider',
    perSeatLabel: 'per seat',
    seatsLeftLabel: '{count} seats left',
    bookButton: 'Book Now',
    detailsButton: 'Details',
    stopLabel: 'stop',
    searchSummaryDate: 'Date',
    searchSummarySeats: '{count} Seats',
    driverRides: '{count} rides',
    kmFromPickup: '{distance} km from pickup',
    durationValue: '{hours}h {minutes}m',
    fetchingRides: 'We are currently fetching best rides for you...',
    noRidesFoundTitle: 'No Rides Found',
    noRidesFoundDesc:
      "We couldn't find any rides for this route and date. Try adjusting your filters or checking a different time.",
  },
  rideFilters: {
    title: 'Filters',
    proximityTitle: 'Proximity',
    nearPickup: 'Near Pickup',
    nearDropoff: 'Near Drop-off',
    departureTimeTitle: 'Departure Time',
    preferencesTitle: 'Preferences',
    seatAvailabilityTitle: 'Seat Availability',
    seatsRequiredLabel: 'Seats Required',
    applyFilters: 'Apply Filters',
    clearAll: 'Clear All',
    noSmoking: 'No Smoking',
    ladiesOnly: 'Ladies Only',
    verifiedDrivers: 'Verified Drivers',
    petFriendly: 'Pet Friendly',
    luggageAllowed: 'Luggage Allowed',
    timeSlot04: '12-4 AM',
    timeSlot48: '4-8 AM',
    timeSlot812: '8-12 AM',
    timeSlot1216: '12-4 PM',
    timeSlot1620: '4-8 PM',
    timeSlot2024: '8-12 PM',
  },
  rideInformation: {
    title: 'Ride Information',
    distanceRemaining: 'Distance remaining',
    driverInfoTitle: 'Host Info',
    carInfoTitle: 'Car Info',
    timelineTitle: 'Timeline',
    rulesTitle: 'Rules',
    amenitiesTitle: 'Amenities',
    fareDetailsTitle: 'Fare Details',
    seatFareLabel: 'Seat Fare',
    serviceFeeLabel: 'Service Fee',
    sustainabilityFeeLabel: 'Sustainability Fee',
    bookSeatButton: 'Book Seat',
    guidelinesNote: 'Please follow the guidelines during the ride.',
    noSmoking: 'No Smoking',
    petsAllowed: 'Pets Allowed',
    freeWifi: 'Free Wi-Fi',
    usbCharging: 'USB Charging',
    fellowTravelers: 'Fellow Travelers',
    journeyComfort: 'Journey Comfort',
    seatsOpen: 'Seats Open',
    departure: 'Departure',
    journey: 'Journey',
    seatsLeft: '{count} seats left',
  },
  selectSeat: {
    title: 'Select Seat',
    subtitle: 'Choose your preferred seat.',
    headerTitle: 'Seat Selection',
    driverLabel: 'Host',
    verifiedVehicle: 'Verified Vehicle',
    arrivingIn: 'Arriving in',
    estimatedFare: 'Estimated Fare',
    legendAvailable: 'Available',
    legendSelected: 'Selected',
    legendBooked: 'Booked',
    legendOccupied: 'Occupied',
    selectVehicleFirst:
      'Please select a vehicle to view the seating arrangement.',
    yourVehicles: 'Your Vehicles',
    summaryTitle: 'Summary',
    seatSelected: 'seat selected',
    seatsSelected: '{count} {seatWord} selected',
    totalPayable: 'Total Payable',
    continue: 'Continue',
    holdTimerNote: 'Your seat is on hold for 5 minutes.',
    pickSeatToContinue: 'Pick a Seat to Continue',
    bookMySeat: 'Book My Seat',
  },
  bookingConfirmed: {
    successTitle: 'Booking Successful!',
    successSubtitle: 'Your ride is confirmed.',
    driverLabel: 'Host',
    verifiedLabel: 'VERIFIED',
    pickupTimeLabel: 'Pickup Time',
    arrivingIn: 'Arriving in {min} mins',
    seatNumberLabel: 'Seat Number',
    windowPreference: 'Window side preferred',
    safetyGuardTitle: 'Safety Guard Active',
    safetyGuardSubtitle: 'Your journey is GPS tracked.',
    primaryCTA: 'Go to My Rides',
    secondaryCTA: 'Share Details',
    plateLabel: 'Plate',
    carbonNeutralTransit: 'Ride Pool Company Carbon Neutral Transit',
    brandTitle: 'ZyncRide',
    seatPositions: {
      driver: 'Host Seat',
      frontPassenger: 'Front (Left)',
      middleLeft: 'Middle (Left)',
      middleCenter: 'Middle (Center)',
      middleRight: 'Middle (Right)',
      backLeft: 'Back (Left)',
      backCenter: 'Back (Center)',
      backRight: 'Back (Right)',
      defaultSeat: 'Seat {id}',
    },
  },
  settings: {
    headerTitle: 'Settings',
    appName: 'ZyncRide',
    notifications: 'Notifications',
    pushNotifications: 'Push Notifications',
    pushNotificationsDesc: 'Enable for ride updates and alerts',
    appearance: 'Appearance',
    theme: 'Theme',
    lightMode: 'Current: Light Mode',
    darkMode: 'Current: Dark Mode',
    darkModeToggle: 'Dark Mode',
    preferences: 'Preferences',
    language: 'Language',
    languageEn: 'English',
    languageHi: 'Hindi',
    region: 'Region',
    emailSettings: 'Email Notifications',
    promotions: 'Promotions',
    rideReceipts: 'Ride Receipts',
    accountSecurity: 'Account Security',
    logout: 'Logout',
    logoutConfirmTitle: 'Logout',
    logoutConfirmMessage:
      'Are you sure you want to logout? You will need to login again to access your account.',
    logoutConfirmButton: 'Logout',
    logoutConfirmCancel: 'Stay logged in',
    version: 'App Version 4.12.0-Verdant',
  },
  myRides: {
    headerTitle: 'My Rides',
    upcomingTab: 'Upcoming',
    draftsTab: 'Drafts',
    completedTab: 'Completed',
    newRequestsTitle: 'New Requests',
    pendingBadge: '{count} Pending',
    publishedRidesTitle: 'Your Rides',
    draftsTitle: 'Drafts',
    clearAll: 'Clear All',
    completedTitle: 'Recently Completed',
    requestsTab: 'Requests',
    archiveTab: 'Archive',
    noUpcomingTitle: 'No upcoming rides',
    noUpcomingDesc: 'Rides you publish will appear here',
    noRequestsTitle: 'No new requests',
    noRequestsDesc: 'Requests for your rides will appear here',
    noDraftsTitle: 'No drafts yet',
    noDraftsDesc: 'Your saved rides will appear here',
    noCompletedTitle: 'No completed rides',
    noCompletedDesc: 'Old rides will appear here',
    noArchiveTitle: 'Empty Archive',
    noArchiveDesc: 'Completed and cancelled rides will appear here',
    cancelRideAlertTitle: 'Cancel Ride',
    cancelRideAlertMsg: 'Are you sure you want to cancel this published ride?',
    cancelRideConfirm: 'Cancel Ride',
    cancelRideKeep: 'Keep Ride',
    cancelRideError: 'Failed to cancel ride.',
    deleteDraftAlertTitle: 'Delete Draft',
    deleteDraftAlertMsg: 'Are you sure you want to remove this draft?',
    deleteDraftConfirm: 'Delete',
    deleteDraftCancel: 'Cancel',
    clearDraftsAlertTitle: 'Clear All Drafts',
    clearDraftsAlertMsg: 'This will remove all your saved ride drafts.',
    clearDraftsConfirm: 'Clear All',
    clearDraftsCancel: 'Cancel',
    startsIn: 'Starts in',
    started: 'Started',
    mins: 'm',
    hours: 'h',
    completedStatus: 'Completed',
    requestPending: 'Request pending',
    rideConfirmed: 'Ride confirmed',
    confirmedStatus: 'Confirmed',
    pendingStatus: 'Pending',
    youAreDriver: 'Ride Host',
    yourVehicle: 'Your Vehicle',
    vehicleDetails: 'Vehicle Details',
  },
  userProfileDetail: {
    headerTitle: 'RideConnect',
    verifiedMember: 'Verified Member',
    preferences: 'Preferences',
    vehicleInfo: 'Vehicle Info',
    viewRatings: 'View breakdown of {{count}} ratings',
    recentReviews: 'Recent Reviews',
    reportUser: 'Report {{name}}',
    bioTitle: 'About Me',
    defaultBio:
      'Verified community partner ready to share rides and reduce carbon footprint! Enjoys meeting new people, listening to soft instrumental music, and promoting safe eco-friendly travels.',
  },
  developer: {
    networkLogsTitle: 'Network Logs',
    noLogsTitle: 'No Network Logs',
    noLogsDesc: 'Make some API calls to see them appear here.',
    clear: 'Clear',
    close: 'Close',
    requestDetails: 'Request Details',
    overview: 'Overview',
    requestHeaders: 'Request Headers',
    requestBody: 'Request Body',
    responseHeaders: 'Response Headers',
    responseBody: 'Response Body',
    pending: 'Pending',
    noBody: 'No body',
    noHeaders: 'No headers',
    copyCurl: 'Copy cURL',
  },
  chatLocation: {
    headerTitle: 'Send Location',
    shareLiveLocation: 'Share Live Location',
    shareLiveLocationDesc: 'Update your location in real-time',
    sendCurrentLocation: 'Send Your Current Location',
    sendCurrentLocationDesc: 'Accurate to 15 meters',
    nearbyPlaces: 'NEARBY PLACES',
    searchPlaceholder: 'Search location...',
    gpsModalTitle: 'GPS Disabled',
    gpsModalMessage:
      'Please enable GPS/location services to center on your current position.',
    enableGps: 'Enable',
    gpsBannerMessage: 'GPS is off. Enable it to locate yourself.',
    gpsSettingsPathAndroid: 'Settings > Location',
    gpsSettingsPathIos: 'Settings > Privacy > Location Services',
    loadingCurrentLocation: 'Loading your current location...',
  },
  rideRoute: {
    title: 'Ride Route',
    locationDetails: 'Location Details',
    openInGoogleMaps: 'Open in Google Maps',
    openInAppleMaps: 'Open in Apple Maps',
  },
  notification: {
    defaultSuccessTitle: 'Success',
    defaultSuccessMessage: 'Action completed successfully.',
    profilePhotoUpdated: 'Profile photo updated successfully',
    defaultErrorTitle: 'Error',
    defaultErrorMessage: 'Something went wrong. Please try again.',
    defaultInfoTitle: 'Information',
    defaultWarningTitle: 'Warning',
    welcomeSuccessTitle: 'Welcome',
    welcomeBack: 'Welcome back to ZyncRide!',
    bookingAccepted: 'Booking accepted successfully.',
    bookingRejected: 'Booking rejected successfully.',
    vehicleRemoved: 'Vehicle removed successfully.',
    vehicleRemoveError: 'Could not delete vehicle. Please try again.',
    mapOpenError: 'Could not open map application',
    activeBookingOverlap:
      'You already have an active booking during this time. Please complete or cancel it first.',
  },
  reportIssue: {
    title: 'Report Issue',
    whatHappenedTitle: 'What happened?',
    whatHappenedSubtitle:
      'Select the category that best describes your concern.',
    categorySafety: 'Safety Concern',
    categoryBehavior: 'Inappropriate Behavior',
    categoryVehicle: 'Vehicle Issue',
    categoryPayment: 'Payment/Price Issue',
    categoryOther: 'Other',
    tellUsMoreTitle: 'Tell us more',
    tellUsMoreSubtitle:
      'Your privacy is our priority. Shared details help us investigate faster.',
    placeholder: 'Describe the incident in detail...',
    safetyExcellentTeam:
      'This report will be handled by our 24/7 Safety Excellence Team.',
    submitReport: 'Submit Report',
    cancel: 'Cancel',
  },
  splash: {
    appName: 'ZyncRide',
    subtitle: 'Smart rides, shared journeys',
    loadingText: 'Preparing your ride...',
  },
  rating: {
    title: 'Share Feedback',
    subtitle: 'Your feedback keeps the ZyncRide community safe and reliable.',
    submitButton: 'Submit Feedback',
    submittingButton: 'Submitting...',
    successTitle: 'Thank You!',
    successMessage: 'Your feedback has been recorded successfully.',
    ratingRequired: 'Please complete all rating parameters.',
    reviewPlaceholder: 'Write a public review (optional)...',
    rateUser: 'Rate {{name}}',
    cameOnTime: 'Punctuality (Came on time)',
    ridingExperience: 'Riding Experience & Safety',
    talkingExperience: 'Communication & Behavior',
    cleanliness: 'Cleanliness & Comfort',
    behavior: 'Behavior & Friendliness',
    overall: 'Overall Experience',
    ratingCardTitle: 'Rate Your Journey',
    ratingCardSubtitle: 'How was your experience with {{name}}?',
    rateButtonText: 'Rate Now',
  },
  suggestions: {
    title: 'Suggestions & Feedback',
    submitTab: 'Submit Feedback',
    historyTab: 'Ticket History',
    categoryLabel: 'Category',
    categoryFeature: 'New Feature Suggestion',
    categoryBug: 'Report an Issue / Bug',
    categoryImprovement: 'Improvement Idea',
    categoryOther: 'Other Suggestions',
    summaryLabel: 'Feedback Summary',
    summaryPlaceholder: 'E.g., Dark Mode support, profile crash',
    descriptionLabel: 'Describe your suggestion or issue',
    descriptionPlaceholder:
      'Please share details, what happened, or your feature idea...',
    screenshotsLabel: 'Attach Screenshots',
    screenshotsDescription:
      'Add up to 5 screenshots to help us understand better',
    addPhoto: 'Add Photo',
    submitButton: 'Submit Feedback',
    submittingButton: 'Submitting...',
    validationErrorCategory: 'Please select a feedback category',
    validationErrorSummary: 'Please enter a feedback summary',
    validationErrorDescription: 'Please enter a description',
    successTitle: 'Feedback Submitted',
    successMessage:
      'Thank you! Your suggestion has been logged as ticket {{ticketNumber}}. Since ZyncRide is new, we will post status updates on this ticket here.',
    ticketNumber: 'Ticket: #{{ticketNumber}}',
    ticketStatusOpen: 'Open',
    ticketStatusInProgress: 'In Progress',
    ticketStatusResolved: 'Resolved',
    ticketStatusUnderReview: 'Under Review',
    ticketCreatedOn: 'Created: {{date}}',
    updatesLabel: 'Updates & Comments',
    noTicketsTitle: 'No Tickets Found',
    noTicketsMessage:
      'You have not submitted any feedback yet. Use the Submit Feedback tab to get started!',
  },
};
