import { Translations } from './types';

export const en: Translations = {
  login: {
    brandName: 'The Digital Curator',
    brandTagline: 'Step into your intentional digital sanctuary.',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '+1 (555) 000-0000',
    phoneError: 'Please enter a valid phone number',
    getOtp: 'Get OTP',
    otpInfoBox: "We'll send a 6-digit code to verify your account securely.",
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    orContinueWith: 'OR CONTINUE WITH',
  },
  otpVerification: {
    titlePrefix: "Confirm it's",
    titleHighlight: 'you',
    subtitle: "We've sent a 6-digit verification code to your registered mobile number:",
    verifyButton: 'Verify Identity',
    verifyingButton: 'Verifying...',
    didNotReceive: "Didn't receive the code?",
    resendNow: 'Resend code now',
    resendIn: 'Resend code in',
    secureAuth: 'Secure Verification',
    needHelp: 'Need help? Chat with Sarah',
    privacyPolicy: 'Privacy Policy',
    supportCenter: 'Support Center',
  },
  profileSetup: {
    headerTitle: 'Verdant Trust',
    heroTitle: 'Welcome home.',
    heroSubtitle: "Let's curate your digital identity to tailor your experience.",
    dobRequiredError: 'Please provide your legal Date of Birth to proceed.',
    identityProfile: 'Identity Profile',
    publicPresence: 'Public Presence',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'E.g. Julianne Reed',
    dobLabel: 'Date of Birth',
    genderLabel: 'Gender',
    genderFemale: 'Female',
    genderMale: 'Male',
    genderOther: 'Other',
    locationPreference: 'Location Preference',
    locationPlaceholder: 'Search your city...',
    nearbyOnly: 'Nearby Only',
    globalReach: 'Global Reach',
    newsletter: 'Newsletter',
    curatedPicks: 'Curated Picks',
    contentPreferences: 'Content Preferences',
    interestDigitalArt: 'Digital Art',
    interestSustainableLiving: 'Sustainable Living',
    interestMinimalism: 'Minimalism',
    interestTypography: 'Typography',
    interestTechEthics: 'Tech Ethics',
    interestArchitecture: 'Architecture',
    almostThere: 'Almost there!',
    identityVerified: 'Your core identity details are verified and secure.',
    completeSetup: 'Complete Setup',
    footerVersion: 'Secure Editorial Environment • v1.0.2',
  },
  profileHub: {
    headerTitle: 'Profile',
    identityVerified: 'Identity Verified',
    proPooler: 'Pro Pooler',
    rating: 'Rating',
    rides: 'Rides',
    memberSince: 'Member Since',
    trustScore: 'Trust Score',
    trustScoreDescr: 'Your consistency makes the community safer and more reliable for everyone.',
    accountManagement: 'Account Management',
    supportLegal: 'Support & Legal',
    editProfile: 'Edit Profile',
    editProfileDescr: 'Name, Bio, and Contact details',
    identityVerification: 'Identity Verification',
    identityVerificationDescr: 'Aadhaar & Vehicle Documentation',
    travelPreferences: 'Travel Preferences',
    travelPreferencesDescr: 'Music, smoking, and pet choices',
    paymentMethods: 'Payment Methods',
    paymentMethodsDescr: 'Wallets, Cards, and UPI',
    ratingsReviews: 'Ratings & Reviews',
    ratingsReviewsDescr: 'Check what others are saying',
    changePassword: 'Change Password',
    changePasswordDescr: 'Security and authentication',
    helpSupport: 'Help & Support',
    aboutUs: 'About Us',
    termsPrivacy: 'Terms & Privacy',
    logout: 'Logout',
    deleteAccount: 'Delete Account',
    navBook: 'BOOK',
    navPublish: 'PUBLISH',
    navMyRides: 'MY RIDES',
    navChats: 'CHATS',
    navProfile: 'PROFILE',
  },
  editProfile: {
    headerTitle: 'Profile',
    successMessage: 'Profile updated successfully!',
    updatePhoto: 'Update Profile Photo',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'E.g. Julianne Reed',
    emailLabel: 'Email Address',
    emailPlaceholder: 'E.g. julianne@sharmyride.com',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '+1 (555) 000-0000',
    dobLabel: 'Date of Birth',
    genderLabel: 'Gender',
    bioLabel: 'Short Bio',
    bioPlaceholder: 'Pro Pooler • Frequent traveler between Downtown and Silicon Valley...',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    fullNameRequired: 'Full name is required',
    fullNameMin: 'Name must be at least 3 characters',
    emailRequired: 'Email address is required',
    emailInvalid: 'Please enter a valid email address',
    phoneRequired: 'Phone number is required',
    phoneInvalid: 'Please enter a valid phone number',
    dobRequired: 'Date of birth is required',
    genderRequired: 'Please select your gender',
    bioMax: 'Bio cannot exceed 200 characters',
  },
  dummyContent: {
    aboutTitle: 'Our Story',
    aboutBody: 'ShareMyRide is more than just a carpooling app. We are a Kinetic Sanctuary—a professional community that values time, reliability, and social connectivity. Founded in 2024, our mission is to turn every commute into an intentional journey of connection and shared productivity.',
    helpTitle: 'Need Assistance?',
    helpBody: 'Whether you are stuck at a pickup point or have a technical glitch, our 24/7 support team is here. Join our community forum or chat with Sarah, our AI assistant, to get instant resolutions for all your queries.',
    termsTitle: 'User Agreement',
    termsBody: 'By using ShareMyRide, you agree to respect our community safety standards. This includes maintaining punctuality, vehicle cleanliness, and verifying your identity through Aadhaar and driving credentials.',
  },
  travelPreferences: {
    headerTitle: 'Travel Preferences',
    heroTitle: 'Your Commute,\nYour Rules.',
    heroSubtitle: 'Personalize your journey sanctuary',
    nonSmoking: 'Non-smoking Ride',
    nonSmokingDescr: 'Prefer vehicles without smoke odor',
    womenOnly: 'Women-only Rides',
    womenOnlyDescr: 'Match only with female drivers/poolers',
    musicPreference: 'Music Preference',
    bollywood: 'Bollywood',
    pop: 'Pop',
    jazz: 'Jazz',
    podcast: 'Podcast',
    silence: 'Silence',
    luggageAllowed: 'Luggage Allowed',
    petFriendly: 'Pet-friendly',
    savePreferences: 'Save Preferences',
    enabled: 'Enabled',
    disabled: 'Disabled',
  },
  vehicleDetails: {
    headerTitle: 'Vehicle Details',
    heroTitle: 'Register Your Vehicle',
    heroSubtitle: 'Help others recognize your ride',
    basicIdentity: 'Basic Identity',
    vehicleCompany: 'Vehicle Company',
    companyPlaceholder: 'e.g. Tesla',
    carModel: 'Car Model',
    modelPlaceholder: 'e.g. Model 3',
    technicalSpecs: 'Technical Specs',
    numberPlate: 'Number Plate',
    platePlaceholder: 'ABC-1234',
    vehicleType: 'Vehicle Type',
    appearance: 'Appearance',
    manufacturingYear: 'Manufacturing Year',
    color: 'Color',
    colorPlaceholder: 'Emerald Green',
    saveVehicle: 'Save Vehicle',
    successMessage: 'Vehicle registered successfully!',
    sedan: 'Sedan',
    suv: 'SUV',
    hatchback: 'Hatchback',
    bike: 'Bike',
  },
};




