import { Translations } from './types';

export const en: Translations = {
  login: {
    brandName: 'The Digital Curator',
    brandTagline: 'Step into your intentional digital sanctuary.',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '+1 (555) 000-0000',
    phoneError: 'Please enter a valid phone number',
    getOtp: 'Get OTP',
    otpInfoBox: "We'll send a 6-digit code to verify your account securely.",
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    orContinueWith: 'OR CONTINUE WITH',
  },
  otpVerification: {
    titlePrefix: "Confirm it's",
    titleHighlight: 'you',
    subtitle: "We've sent a 6-digit verification code to your registered mobile number:",
    verifyButton: 'Verify Identity',
    verifyingButton: 'Verifying...',
    didNotReceive: "Didn't receive the code?",
    resendNow: 'Resend code now',
    resendIn: 'Resend code in',
    secureAuth: 'Secure Verification',
    needHelp: 'Need help? Chat with Sarah',
    privacyPolicy: 'Privacy Policy',
    supportCenter: 'Support Center',
  },
  profileSetup: {
    headerTitle: 'Verdant Trust',
    heroTitle: 'Welcome home.',
    heroSubtitle: "Let's curate your digital identity to tailor your experience.",
    dobRequiredError: 'Please provide your legal Date of Birth to proceed.',
    identityProfile: 'Identity Profile',
    publicPresence: 'Public Presence',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'E.g. Julianne Reed',
    dobLabel: 'Date of Birth',
    genderLabel: 'Gender',
    genderFemale: 'Female',
    genderMale: 'Male',
    genderOther: 'Other',
    locationPreference: 'Location Preference',
    locationPlaceholder: 'Search your city...',
    nearbyOnly: 'Nearby Only',
    globalReach: 'Global Reach',
    newsletter: 'Newsletter',
    curatedPicks: 'Curated Picks',
    contentPreferences: 'Content Preferences',
    interestDigitalArt: 'Digital Art',
    interestSustainableLiving: 'Sustainable Living',
    interestMinimalism: 'Minimalism',
    interestTypography: 'Typography',
    interestTechEthics: 'Tech Ethics',
    interestArchitecture: 'Architecture',
    almostThere: 'Almost there!',
    identityVerified: 'Your core identity details are verified and secure.',
    completeSetup: 'Complete Setup',
    footerVersion: 'Secure Editorial Environment • v1.0.2',
  },
  profileHub: {
    headerTitle: 'Profile',
    identityVerified: 'Identity Verified',
    proPooler: 'Pro Pooler',
    rating: 'Rating',
    rides: 'Rides',
    memberSince: 'Member Since',
    trustScore: 'Trust Score',
    trustScoreDescr: 'Your consistency makes the community safer and more reliable for everyone.',
    accountManagement: 'Account Management',
    supportLegal: 'Support & Legal',
    editProfile: 'Edit Profile',
    editProfileDescr: 'Name, Bio, and Contact details',
    identityVerification: 'Identity Verification',
    identityVerificationDescr: 'Aadhaar & Vehicle Documentation',
    travelPreferences: 'Travel Preferences',
    travelPreferencesDescr: 'Music, smoking, and pet choices',
    paymentMethods: 'Payment Methods',
    paymentMethodsDescr: 'Wallets, Cards, and UPI',
    ratingsReviews: 'Ratings & Reviews',
    ratingsReviewsDescr: 'Check what others are saying',
    changePassword: 'Change Password',
    changePasswordDescr: 'Security and authentication',
    helpSupport: 'Help & Support',
    aboutUs: 'About Us',
    termsPrivacy: 'Terms & Privacy',
    logout: 'Logout',
    deleteAccount: 'Delete Account',
    navBook: 'BOOK',
    navPublish: 'PUBLISH',
    navMyRides: 'MY RIDES',
    navChats: 'CHATS',
    navProfile: 'PROFILE',
  },
  editProfile: {
    headerTitle: 'Profile',
    successMessage: 'Profile updated successfully!',
    updatePhoto: 'Update Profile Photo',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'E.g. Julianne Reed',
    emailLabel: 'Email Address',
    emailPlaceholder: 'E.g. julianne@sharmyride.com',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '+1 (555) 000-0000',
    dobLabel: 'Date of Birth',
    genderLabel: 'Gender',
    bioLabel: 'Short Bio',
    bioPlaceholder: 'Pro Pooler • Frequent traveler between Downtown and Silicon Valley...',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    fullNameRequired: 'Full name is required',
    fullNameMin: 'Name must be at least 3 characters',
    emailRequired: 'Email address is required',
    emailInvalid: 'Please enter a valid email address',
    phoneRequired: 'Phone number is required',
    phoneInvalid: 'Please enter a valid phone number',
    dobRequired: 'Date of birth is required',
    genderRequired: 'Please select your gender',
    bioMax: 'Bio cannot exceed 200 characters',
  },
  dummyContent: {
    aboutTitle: 'Our Story',
    aboutBody: 'ShareMyRide is more than just a carpooling app. We are a Kinetic Sanctuary—a professional community that values time, reliability, and social connectivity. Founded in 2024, our mission is to turn every commute into an intentional journey of connection and shared productivity.',
    helpTitle: 'Need Assistance?',
    helpBody: 'Whether you are stuck at a pickup point or have a technical glitch, our 24/7 support team is here. Join our community forum or chat with Sarah, our AI assistant, to get instant resolutions for all your queries.',
    termsTitle: 'User Agreement',
    termsBody: 'By using ShareMyRide, you agree to respect our community safety standards. This includes maintaining punctuality, vehicle cleanliness, and verifying your identity through Aadhaar and driving credentials.',
  },
  travelPreferences: {
    headerTitle: 'Travel Preferences',
    heroTitle: 'Your Commute,\nYour Rules.',
    heroSubtitle: 'Personalize your journey sanctuary',
    nonSmoking: 'Non-smoking Ride',
    nonSmokingDescr: 'Prefer vehicles without smoke odor',
    womenOnly: 'Women-only Rides',
    womenOnlyDescr: 'Match only with female drivers/poolers',
    musicPreference: 'Music Preference',
    bollywood: 'Bollywood',
    pop: 'Pop',
    jazz: 'Jazz',
    podcast: 'Podcast',
    silence: 'Silence',
    luggageAllowed: 'Luggage Allowed',
    petFriendly: 'Pet-friendly',
    savePreferences: 'Save Preferences',
    enabled: 'Enabled',
    disabled: 'Disabled',
  },
  vehicleDetails: {
    headerTitle: 'Vehicle Details',
    heroTitle: 'Register Your Vehicle',
    heroSubtitle: 'Help others recognize your ride',
    basicIdentity: 'Basic Identity',
    vehicleCompany: 'Vehicle Company',
    companyPlaceholder: 'e.g. Tesla',
    carModel: 'Car Model',
    modelPlaceholder: 'e.g. Model 3',
    technicalSpecs: 'Technical Specs',
    numberPlate: 'Number Plate',
    platePlaceholder: 'ABC-1234',
    vehicleType: 'Vehicle Type',
    appearance: 'Appearance',
    manufacturingYear: 'Manufacturing Year',
    color: 'Color',
    colorPlaceholder: 'Emerald Green',
    saveVehicle: 'Save Vehicle',
    successMessage: 'Vehicle registered successfully!',
    bike: 'Bike',
    hatchback: 'Hatchback',
    suv: 'SUV',
    sedan: 'Sedan',
  },
  chat: {
    headerTitle: 'Messages',
    searchPlaceholder: 'Search conversations...',
    recentMessages: 'Recent Messages',
    noMessages: 'No messages yet',
    newMessage: 'New Message',
    rideLabel: 'Ride:',
    yesterday: 'Yesterday',
    activeDrivers: 'Active Drivers',
  },
  rideDetails: {
    headerTitle: 'My Rides',
    liveTracking: 'Live Tracking',
    pickupLabel: 'Pickup',
    stopLabel: 'Stop {count}',
    destinationLabel: 'Destination',
    estimatedArrival: 'Estimated Arrival',
    minsAway: '{count} mins away',
    totalFare: 'Total Fare',
    verified: 'Verified',
    otherRiders: 'Other Riders',
    spotsLeft: '{count} Spots Left',
    coRider: 'Co-rider',
    joiningAt: 'Joining {stop}',
    trustTitle: 'Verdant Trust Protection',
    trustDescription: 'Your ride is covered by our comprehensive safety protocols. Real-time emergency sharing is active.',
    cancelRide: 'Cancel Ride',
    chat: 'Chat',
  },
  cancelRide: {
    title: 'Cancel Ride?',
    subtitle: 'Please let us know why you’re cancelling. This helps us improve your ride experience.',
    reasonDriverFar: 'Driver is too far',
    reasonChangedMind: 'Changed my mind',
    reasonCheaperRide: 'Found a cheaper ride',
    reasonWaitLong: 'Wait time is too long',
    reasonOther: 'Other reason',
    confirmCancel: 'Confirm Cancellation',
    keepRide: 'Keep My Ride',
    otherReasonPlaceholder: 'Please specify...',
  },
  locationSelection: {
    titlePrefix: 'Where are we ',
    titleHighlight: 'drifting',
    titleSuffix: ' to?',
    subtitle: "Let's start your journey by picking the coordinates.",
    startLabel: 'Starting Point',
    startPlaceholder: 'Pick-up location...',
    destinationLabel: 'Final Destination',
    destinationPlaceholder: 'Where to?',
    continueJourney: 'Continue Journey',
    contextualInfo: 'Your location remains private until you confirm a drift partner. Precision is key for the best matches.',
  },
  mapPicker: {
    title: 'Pick your location',
    searchPlaceholder: 'Search location...',
    setPickup: 'SET PICKUP',
    setDestination: 'SET DESTINATION',
    selectedArea: 'Selected Area',
    selectLocation: 'Select Location',
  },
  routeSelection: {
    headerTitle: 'Publish Ride',
    stepIndicator: 'STEP 2/9',
    title: 'Select your route',
    subtitle: 'Choose the path that works best for your journey and passengers.',
    recommended: 'RECOMMENDED',
    trustBadge: 'Our algorithm analyzed 1.2M patterns to suggest these optimized transit routes for your safety.',
    continue: 'Continue',
  },
  middleStops: {
    headerTitle: 'Publish Ride',
    stepIndicator: '3 / 9',
    title: 'Plan your route',
    subtitle: "Add stops where you're comfortable picking up or dropping off passengers.",
    startPointLabel: 'Start Point',
    stopLabel: 'Stop',
    addMiddleStop: 'Add Middle Stop',
    addMiddleStopSub: 'Click to open map',
    destinationLabel: 'Destination',
    optimizedRoute: 'OPTIMIZED ROUTE',
    continue: 'Continue',
  },
  middleStopMap: {
    headerTitle: 'Publish Ride',
    stepIndicator: 'Step 3 of 5',
    searchPlaceholder: 'Search for a stop along the route...',
    whereWillYouStop: 'Where will you stop?',
    addingStopsIncreasesInfo: 'Adding middle stops increases your chances of finding passengers by up to',
    suggestedStoppages: 'SUGGESTED STOPPAGES',
    popular: 'POPULAR',
    quickExit: 'QUICK EXIT',
    recentHistory: 'RECENT HISTORY',
    currentRoute: 'CURRENT ROUTE',
    selectedStop: 'SELECTED STOP',
    addedStops: 'ADDED STOPS',
    continue: 'Continue',
  },
  dateSelection: {
    headerTitle: 'Publish Ride',
    stepIndicator: 'Step 4/9',
    title: 'When are you going?',
    subtitle: 'Date Selection',
    currentLabel: 'Current',
    daysOfWeek: ['MO', 'TU', 'WE', 'TH', 'FR', 'SA', 'SU'],
    selectedDate: 'Selected Date',
    noneSelected: 'Please select a date',
    next: 'Next',
  },
  timeSelection: {
    headerTitle: 'Publish Ride',
    stepIndicator: 'Step 5/9',
    title: 'When are you',
    titleHighlight: 'departing?',
    subtitle: 'Set your departure time for your journey.',
    selectedTimeLabel: 'Selected Time',
    formatLabel: '24-HOUR FORMAT',
    arrivalNote: 'Your estimated arrival is based on live traffic data.',
    continue: 'Continue',
  },
  seatSelection: {
    headerTitle: 'Publish Ride',
    stepIndicator: 'Step 6/9',
    title: 'Select Available Seats',
    subtitle: "Tap on the seats you'd like to offer for this journey.",
    fiveSeater: '5 Seater',
    sevenSeater: '7 Seater',
    driverLabel: 'Driver',
    legendSelected: 'Selected',
    legendAvailable: 'Available',
    legendOccupied: 'Occupied',
    seatsOffering: 'Seats Offering',
    estEarnings: 'Est. Earnings',
    continue: 'Continue',
  },
  priceSelection: {
    headerTitle: 'Publish Ride',
    title: 'Set your price',
    subtitle: 'Based on your route and distance, we suggest a fair price per passenger.',
    basePriceLabel: 'Base Price per seat',
    recommendedBadge: 'Recommended Price',
    frontSeatPremiumTitle: 'Add front seat premium',
    frontSeatPremiumDesc: 'Offer the front seat for passengers who want extra leg space. You can charge up to 10% more for this seat.',
    premiumAmountLabel: 'Premium amount',
    maxLimitNote: 'Max limit reached (+10%)',
    multiStopTitle: 'Multi-stop journey detected',
    multiStopSubtitle: 'You have 2 stops between your start and destination.',
    customizePricing: 'Customize stop-to-stop pricing',
    continueButton: 'Continue to Review',
    segmentSheetTitle: 'Segment Pricing',
    segmentSheetSubtitle: 'Adjust prices for each part of your journey',
    segmentLabel: 'Segment',
    minPriceLabel: 'Min Price',
    maxPriceLabel: 'Max Price',
    cancelButton: 'Cancel',
    saveButton: 'Save Ranges',
    frontSeatProjectedLabel: 'Front Seat Price',
  },
  requestType: {
    headerTitle: 'Publish Ride',
    title: 'How should passengers join?',
    subtitle: 'Decide if you want to manually approve every request or let travelers book instantly.',
    instantBookingTitle: 'Instant Booking',
    instantBookingSubtitle: 'Passengers can book without waiting for your approval. Best for filling seats fast.',
    requestReviewTitle: 'Request & Review',
    requestReviewSubtitle: 'Review passenger profiles and reviews before confirming. Total control of your ride.',
    proTipTitle: 'PRO TIP',
    proTipText: '"Instant Booking rides are 3x more likely to be fully booked. Travelers love the convenience of immediate confirmation."',
    continueButton: 'Continue',
  },
  summaryPublish: {
    headerTitle: 'Publish Ride',
    title: 'Review Drift',
    subtitle: 'Confirm your journey details before we take it live.',
    departureLabel: 'Departure',
    arrivalLabel: 'Arrival',
    vehicleLabel: 'Vehicle',
    availabilityLabel: 'Availability',
    ridePreferencesLabel: 'Ride Preferences',
    noSmoking: 'No Smoking',
    petsAllowed: 'Pets Allowed',
    chillMusic: 'Chill Music',
    publishRideButton: 'Publish Ride',
    termsText1: 'By publishing, you agree to our ',
    termsLink: 'Safety Guidelines',
    termsText2: ' and community policies.',
  },
  publishSuccess: {
    title: 'Publish Successful!',
    subtitle: 'Your ride is now live and travelers can start sending requests.',
    infoTitle: 'SAFETY GUARD ACTIVE',
    infoText: 'Your journey is GPS tracked and insured by Kinetic Sanctuary. Passenger identity verification is mandatory for every ride.',
    primaryCTA: 'Go to My Rides',
    secondaryCTA: 'Share Trip Details',
  },
  bookRideInfo: {
    heroTitle: 'Where to next?',
    heroSubtitle: 'Plan your sustainable journey in seconds.',
    pickupLabel: 'Pickup Location',
    pickupPlaceholder: 'Current Location',
    destinationLabel: 'Destination',
    destinationPlaceholder: 'Enter destination',
    travelDateLabel: 'Travel Date',
    peopleCountLabel: 'Number of People',
    peopleCountSub: 'Including yourself',
    searchButton: 'Search Available Rides',
    recentSearchesTitle: 'Recent Searches',
    clearAll: 'Clear all',
    trustTitle: 'Safe and Verified',
    trustDescription: 'Every pool member in Kinetic Sanctuary is identity-verified. Ride with peace of mind in our vetted community.',
  },
  availableRides: {
    heroTitle: 'Available Rides',
    heroSubtitle: 'Choose your sustainable drift partner.',
    timeFilterLabel: 'Time',
    noSmokingFilterLabel: 'No Smoking',
    ladiesOnlyFilterLabel: 'Ladies Only',
    topRatedFilterLabel: 'Top Rated',
    frequentCoRiderBadge: 'Frequent Co-rider',
    perSeatLabel: 'Per Seat',
    seatsLeftLabel: '{count} Seats left',
    bookButton: 'Book',
    detailsButton: 'Details',
    stopLabel: 'Stop: {location}',
    searchSummaryDate: 'Tomorrow, 14 Oct',
    searchSummarySeats: '{count} Seats',
  },
  rideFilters: {
    title: 'Filter Rides',
    proximityTitle: 'Proximity',
    nearPickup: 'Near Pickup',
    nearDropoff: 'Near Drop-off',
    departureTimeTitle: 'Departure Time',
    preferencesTitle: 'Preferences',
    seatAvailabilityTitle: 'Seat Availability',
    seatsRequiredLabel: 'Seats required',
    applyFilters: 'Apply Filters',
    clearAll: 'Clear All',
  },
  rideInformation: {
    title: 'Ride Details',
    distanceRemaining: '{distance} miles remaining',
    driverInfoTitle: 'Driver Info',
    carInfoTitle: 'Car Info',
    timelineTitle: 'Route Timeline',
    rulesTitle: 'Ride Rules',
    amenitiesTitle: 'Amenities',
    fareDetailsTitle: 'Fare Details',
    seatFareLabel: 'Seat fare (1 person)',
    serviceFeeLabel: 'Platform service fee',
    sustainabilityFeeLabel: 'Sustainability offset',
    bookSeatButton: 'Book Seat',
    guidelinesNote: 'By booking, you agree to our Community Guidelines and Cancellation Policy.',
    noSmoking: 'No Smoking',
    petsAllowed: 'Pets Allowed',
    freeWifi: 'Free Wi-Fi',
    usbCharging: 'USB Charging',
  },
  selectSeat: {
    title: 'Select Seat',
    subtitle: 'Tap a seat to reserve it',
    headerTitle: 'Select Seat',
    driverLabel: 'Driver',
    verifiedVehicle: 'Verified Electric',
    arrivingIn: 'Arriving in {min} mins',
    estimatedFare: 'ESTIMATED FARE',
    legendAvailable: 'Available',
    legendSelected: 'Selected',
    legendBooked: 'Booked',
    summaryTitle: 'Reservation Summary',
    seatSelected: '{count} Seat selected',
    totalPayable: 'Total Payable',
    continue: 'Continue',
    holdTimerNote: 'Seats are held for 5:00 minutes to ensure a fair booking experience.',
  },
};






