import { Translations } from './types';

export const hi: Translations = {
  login: {
    brandName: 'द डिजिटल क्यूरेटर',
    brandTagline: 'अपने डिजिटल अभयारण्य में कदम रखें।',
    phoneLabel: 'फ़ोन नंबर',
    phonePlaceholder: '+91 98765 43210',
    phoneError: 'कृपया एक वैध फ़ोन नंबर दर्ज करें',
    getOtp: 'OTP प्राप्त करें',
    otpInfoBox: 'आपके खाते को सुरक्षित रूप से सत्यापित करने के लिए हम 6-अंकीय कोड भेजेंगे।',
    noAccount: 'खाता नहीं है?',
    signUp: 'साइन अप करें',
    orContinueWith: 'या इसके साथ जारी रखें',
  },
  otpVerification: {
    titlePrefix: 'पुष्टि करें कि यह',
    titleHighlight: 'आप',
    subtitle: 'हमने आपके पंजीकृत मोबाइल नंबर पर 6 अंकों का सत्यापन कोड भेजा है:',
    verifyButton: 'पहचान सत्यापित करें',
    verifyingButton: 'सत्यापित किया जा रहा है...',
    didNotReceive: 'कोड प्राप्त नहीं हुआ?',
    resendNow: 'अभी कोड फिर से भेजें',
    resendIn: 'में कोड फिर से भेजें',
    secureAuth: 'सुरक्षित सत्यापन',
    needHelp: 'मदद चाहिए? सारा से चैट करें',
    privacyPolicy: 'गोपनीयता नीति',
    supportCenter: 'सहायता केंद्र',
  },
  profileSetup: {
    headerTitle: 'वरदंत ट्रस्ट',
    heroTitle: 'घर वापसी पर स्वागत है।',
    heroSubtitle: 'आइए आपके अनुभव को बेहतर बनाने के लिए आपकी डिजिटल पहचान को व्यवस्थित करें।',
    dobRequiredError: 'आगे बढ़ने के लिए कृपया अपनी कानूनी जन्म तिथि प्रदान करें।',
    identityProfile: 'पहचान प्रोफ़ाइल',
    publicPresence: 'सार्वजनिक उपस्थिति',
    fullNameLabel: 'पूरा नाम',
    fullNamePlaceholder: 'उदा. जूलियन रीड',
    dobLabel: 'जन्म तिथि',
    genderLabel: 'लिंग',
    genderFemale: 'महिला',
    genderMale: 'पुरुष',
    genderOther: 'अन्य',
    locationPreference: 'स्थान वरीयता',
    locationPlaceholder: 'अपना शहर खोजें...',
    nearbyOnly: 'केवल पास के',
    globalReach: 'वैश्विक पहुंच',
    newsletter: 'न्यूज़लेटर',
    curatedPicks: 'क्यूरेटेड पिक्स',
    contentPreferences: 'सामग्री प्राथमिकताएं',
    interestDigitalArt: 'डिजिटल आर्ट',
    interestSustainableLiving: 'सतत जीवन',
    interestMinimalism: 'न्यूनतमवाद',
    interestTypography: 'टाइपोग्राफी',
    interestTechEthics: 'टेक एथिक्स',
    interestArchitecture: 'आर्किटेक्चर',
    almostThere: 'लगभग वहां!',
    identityVerified: 'आपके मुख्य पहचान विवरण सत्यापित और सुरक्षित हैं।',
    completeSetup: 'सेटअप पूरा करें',
    footerVersion: 'सुरक्षित संपादकीय वातावरण • v1.0.2',
  },
  profileHub: {
    headerTitle: 'प्रोफ़ाइल',
    identityVerified: 'पहचान सत्यापित',
    proPooler: 'प्रो पूलर',
    rating: 'रेटिंग',
    rides: 'सवारियां',
    memberSince: 'सदस्यता की शुरुआत',
    trustScore: 'विश्वास स्कोर',
    trustScoreDescr: 'आपकी निरंतरता समुदाय को सभी के लिए सुरक्षित और अधिक विश्वसनीय बनाती है।',
    accountManagement: 'खाता प्रबंधन',
    supportLegal: 'सहायता और कानूनी',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    editProfileDescr: 'नाम, बायो और संपर्क विवरण',
    identityVerification: 'पहचान सत्यापन',
    identityVerificationDescr: 'आधार और वाहन दस्तावेज़',
    travelPreferences: 'यात्रा प्राथमिकताएं',
    travelPreferencesDescr: 'संगीत, धूम्रपान और पालतू जानवरों के विकल्प',
    paymentMethods: 'भुगतान के तरीके',
    paymentMethodsDescr: 'वॉलेट, कार्ड और UPI',
    ratingsReviews: 'रेटिंग और समीक्षाएं',
    ratingsReviewsDescr: 'देखें कि दूसरे क्या कह रहे हैं',
    changePassword: 'पासवर्ड बदलें',
    changePasswordDescr: 'सुरक्षा और प्रमाणीकरण',
    helpSupport: 'सहायता और समर्थन',
    aboutUs: 'हमारे बारे में',
    termsPrivacy: 'शर्तें और गोपनीयता',
    logout: 'लॉगआउट',
    deleteAccount: 'खाता हटाएं',
    navBook: 'बुक करें',
    navPublish: 'प्रकाशित करें',
    navMyRides: 'मेरी सवारी',
    navChats: 'चैट',
    navProfile: 'प्रोफ़ाइल',
  },
};

