import { Translations } from './types';

export const hi: Translations = {
  common: {
    save: 'सहेजें',
    edit: 'संपादित करें',
    cancel: 'रद्द करें',
    done: 'हो गया',
    loading: 'लोड हो रहा है...',
    next: 'अगला',
    back: 'पीछे',
    delete: 'हटाएं',
    clear: 'साफ करें',
    confirm: 'पुष्टि करें',
    copied: 'कॉपी किया गया!',
    pickup: 'पिकअप',
    dropoff: 'ड्रॉप-ऑफ',
    stop: 'स्टॉप',
    vehicle: 'वाहन',
    pricing: 'मूल्य निर्धारण',
    preferences: 'प्राथमिकताएं',
    today: 'आज',
    openingMap: 'मैप खोला जा रहा है',
    navigatingTo: 'नेविगेट किया जा रहा है',
    addressCopied: 'पता कॉपी किया गया',
    success: 'सफलता',
    error: 'त्रुटि',
  },
  login: {
    brandName: 'The RPC',
    brandTagline: 'सत्यापित समुदाय भागीदारों के साथ अपनी यात्रा नेविगेट करें।',
    phoneLabel: 'फोन नंबर',
    phonePlaceholder: '1234567890',
    phoneError: 'कृपया एक वैध फोन नंबर दर्ज करें',
    getOtp: 'ओटीपी प्राप्त करें',
    otpInfoBox: 'हम आपके खाते को सुरक्षित रूप से सत्यापित करने के लिए 6-अंकीय कोड भेजेंगे।',
    noAccount: 'खाता नहीं है?',
    signUp: 'साइन अप करें',
    orContinueWith: 'या इसके साथ जारी रखें',
  },
  otpVerification: {
    titlePrefix: 'पुष्टि करें कि यह',
    titleHighlight: 'आप',
    screenName: 'ओटीपी सत्यापन',
    subtitle: 'हमने आपके पंजीकृत मोबाइल नंबर पर 6-अंकीय सत्यापन कोड भेजा है:',
    verifyButton: 'पहचान सत्यापित करें',
    verifyingButton: 'सत्यापित किया जा रहा है...',
    didNotReceive: 'कोड प्राप्त नहीं हुआ?',
    resendNow: 'अब कोड पुन: भेजें',
    resendIn: 'कोड पुन: भेजें',
    secureAuth: 'सुरक्षित सत्यापन',
    needHelp: 'मदद चाहिए? सारा के साथ चैट करें',
    privacyPolicy: 'गोपनीयता नीति',
    supportCenter: 'सहायता केंद्र',
  },
  profileSetup: {
    headerTitle: 'वर्डेंट ट्रस्ट',
    heroTitle: 'घर वापसी पर स्वागत है।',
    heroSubtitle: 'आइए आपके अनुभव को बेहतर बनाने के लिए आपकी डिजिटल पहचान को व्यवस्थित करें।',
    dobRequiredError: 'आगे बढ़ने के लिए कृपया अपनी कानूनी जन्म तिथि प्रदान करें।',
    requiredFieldsError: 'जारी रखने के लिए कृपया सभी अनिवार्य फ़ील्ड भरें।',
    identityProfile: 'पहचान प्रोफाइल',
    publicPresence: 'सार्वजनिक उपस्थिति',
    fullNameLabel: 'पूरा नाम',
    fullNamePlaceholder: 'उदा. जूलियन रीड',
    dobLabel: 'जन्म तिथि',
    genderLabel: 'लिंग',
    genderFemale: 'महिला',
    genderMale: 'पुरुष',
    genderOther: 'अन्य',
    locationPreference: 'स्थान वरीयता',
    locationPlaceholder: 'अपना शहर खोजें...',
    nearbyOnly: 'केवल पास के',
    globalReach: 'वैश्विक पहुंच',
    newsletter: 'न्यूज़लेटर',
    personalizedSuggestions: 'व्यक्तिगत सुझाव',
    contentPreferences: 'सामग्री प्राथमिकताएं',
    interestDigitalArt: 'डिजिटल आर्ट',
    interestSustainableLiving: 'सतत जीवन',
    interestMinimalism: 'मिनिमलिज्म',
    interestTypography: 'टाइपोग्राफी',
    interestTechEthics: 'टेक एथिक्स',
    interestArchitecture: 'आर्किटेक्चर',
    almostThere: 'बस पहुँच गए!',
    identityVerified: 'आपकी मूल पहचान विवरण सत्यापित और सुरक्षित हैं।',
    completeSetup: 'सेटअप पूरा करें',
    footerVersion: 'सुरक्षित संपादकीय वातावरण • v1.0.2',
  },
  profileHub: {
    headerTitle: 'प्रोफ़ाइल',
    identityVerified: 'पहचान सत्यापित',
    proPooler: 'प्रो पूलर',
    rating: 'रेटिंग',
    rides: 'सवारी',
    memberSince: 'से सदस्य',
    trustScore: 'ट्रस्ट स्कोर',
    trustScoreDescr: 'आपकी निरंतरता समुदाय को सभी के लिए सुरक्षित और अधिक विश्वसनीय बनाती है।',
    accountManagement: 'खाता प्रबंधन',
    supportLegal: 'सहायता और कानूनी',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    editProfileDescr: 'नाम, बायो और संपर्क विवरण',
    identityVerification: 'पहचान सत्यापन',
    identityVerificationDescr: 'आधार और वाहन दस्तावेज',
    travelPreferences: 'यात्रा प्राथमिकताएं',
    travelPreferencesDescr: 'संगीत, धूम्रपान और पालतू जानवरों की पसंद',
    paymentMethods: 'भुगतान के तरीके',
    paymentMethodsDescr: 'वॉलेट, कार्ड और यूपीआई',
    ratingsReviews: 'रेटिंग और समीक्षाएं',
    ratingsReviewsDescr: 'देखें कि दूसरे क्या कह रहे हैं',
    changePassword: 'पासवर्ड बदलें',
    changePasswordDescr: 'सुरक्षा और प्रमाणीकरण',
    helpSupport: 'सहायता और समर्थन',
    aboutUs: 'हमारे बारे में',
    termsPrivacy: 'शर्तें और गोपनीयता',
    logout: 'लॉगआउट',
    deleteAccount: 'खाता हटाएं',
    navBook: 'बुक',
    navPublish: 'प्रकाशित करें',
    navMyRides: 'मेरी सवारी',
    navChats: 'चैट',
    navProfile: 'प्रोफ़ाइल',
  },
  editProfile: {
    headerTitle: 'प्रोफ़ाइल संपादित करें',
    successMessage: 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई',
    updatePhoto: 'फोटो अपडेट करें',
    fullNameLabel: 'पूरा नाम',
    fullNamePlaceholder: 'अपना पूरा नाम दर्ज करें',
    emailLabel: 'ईमेल पता',
    emailPlaceholder: 'अपना ईमेल दर्ज करें',
    phoneLabel: 'फोन नंबर',
    phonePlaceholder: 'अपना फोन नंबर दर्ज करें',
    dobLabel: 'जन्म तिथि',
    genderLabel: 'लिंग',
    bioLabel: 'बायो',
    bioPlaceholder: 'अपने बारे में थोड़ा बताएं',
    cancel: 'रद्द करें',
    saveChanges: 'परिवर्तन सहेजें',
    fullNameRequired: 'पूरा नाम अनिवार्य है',
    fullNameMin: 'नाम कम से कम 3 अक्षरों का होना चाहिए',
    emailRequired: 'ईमेल अनिवार्य है',
    emailInvalid: 'कृपया एक वैध ईमेल दर्ज करें',
    phoneRequired: 'फोन नंबर अनिवार्य है',
    phoneInvalid: 'कृपया एक वैध फोन नंबर दर्ज करें',
    dobRequired: 'जन्म तिथि अनिवार्य है',
    genderRequired: 'लिंग अनिवार्य है',
    bioMax: 'बायो 150 अक्षरों से अधिक नहीं हो सकता',
  },
  dummyContent: {
    aboutTitle: 'हमारे बारे में',
    aboutBody: 'राइडपूलकंपनी यात्रियों को सुरक्षित और कुशल तरीके से जोड़ने के लिए समर्पित है।',
    helpTitle: 'सहायता केंद्र',
    helpBody: 'यदि आपके कोई प्रश्न हैं, तो कृपया हमारी सहायता टीम से संपर्क करें।',
    termsTitle: 'नियम और शर्तें',
    termsBody: 'हमारी सेवा का उपयोग करके, आप हमारे नियमों और शर्तों से सहमत होते हैं।',
  },
  travelPreferences: {
    headerTitle: 'यात्रा प्राथमिकताएं',
    heroTitle: 'अपनी यात्रा को आकार दें।',
    heroSubtitle: 'सह-यात्रियों को बताएं कि आप क्या पसंद करते हैं।',
    nonSmoking: 'धूम्रपान रहित',
    nonSmokingDescr: 'सवारी के दौरान धूम्रपान नहीं',
    womenOnly: 'केवल महिलाएं',
    womenOnlyDescr: 'महिला सह-यात्रियों को प्राथमिकता दें',
    musicPreference: 'संगीत प्राथमिकता',
    bollywood: 'बॉलीवुड',
    pop: 'पॉप',
    jazz: 'जैज',
    podcast: 'पॉडकास्ट',
    silence: 'शांति',
    luggageAllowed: 'सामान की अनुमति है',
    petFriendly: 'पेट फ्रेंडली',
    manualApproval: 'मैनुअल अनुमोदन',
    manualApprovalDescr: 'चालक बुकिंग अनुरोधों को मंजूरी देता है',
    waitingTime: 'प्रतीक्षा समय',
    waitingTimeDescr: 'पिकअप पर चालक द्वारा प्रतीक्षा करने का अधिकतम समय',
    savePreferences: 'प्राथमिकताएं सहेजें',
    enabled: 'सक्षम',
    disabled: 'अक्षम',
  },
  vehicleDetails: {
    headerTitle: 'वाहन विवरण',
    heroTitle: 'अपनी सवारी पंजीकृत करें।',
    heroSubtitle: 'सत्यापन और पहचान के लिए वाहन विवरण जोड़ें।',
    basicIdentity: 'मूल पहचान',
    vehicleCompany: 'वाहन कंपनी',
    companyPlaceholder: 'उदा. हुंडई',
    carModel: 'कार मॉडल',
    modelPlaceholder: 'उदा. i20',
    technicalSpecs: 'तकनीकी विनिर्देश',
    numberPlate: 'नंबर प्लेट',
    platePlaceholder: 'उदा. DL 01 AB 1234',
    vehicleType: 'वाहन का प्रकार',
    appearance: 'दिखावट',
    manufacturingYear: 'निर्माण का वर्ष',
    color: 'रंग',
    colorPlaceholder: 'उदा. सफेद',
    saveVehicle: 'वाहन सहेजें',
    successMessage: 'वाहन सफलतापूर्वक सहेजा गया',
    sedan: 'सेडान',
    suv: 'एसयूवी',
    hatchback: 'हैचबैक',
    bike: 'बाइक',
    capacity: 'क्षमता',
    seaterCount: 'सीटों की संख्या',
    seater5: '5 सीटर',
    seater7: '7 सीटर',
  },
  chat: {
    headerTitle: 'चैट',
    searchPlaceholder: 'संपर्क या संदेश खोजें...',
    recentMessages: 'हाल के संदेश',
    noMessages: 'अभी तक कोई संदेश नहीं',
    newMessage: 'नया संदेश',
    rideLabel: 'सवारी',
    yesterday: 'कल',
    activeDrivers: 'सक्रिय चालक',
  },
  rideDetails: {
    headerTitle: 'सवारी का विवरण',
    timelineTitle: 'यात्रा का विवरण',
    fetchingDetails: 'आपके लिए सवारी विवरण तैयार किया जा रहा है...',
    liveTracking: 'लाइव ट्रैकिंग',
    pickupLabel: 'पिकअप',
    stopLabel: 'स्टॉप',
    destinationLabel: 'गंतव्य',
    estimatedArrival: 'अनुमानित आगमन',
    minsAway: 'मिनट दूर',
    totalFare: 'कुल किराया',
    verified: 'सत्यापित',
    otherRiders: 'अन्य यात्री',
    spotsLeft: 'स्थान शेष',
    coRider: 'सह-यात्री',
    joiningAt: 'पर शामिल हो रहे हैं',
    trustTitle: 'भरोसेमंद सवारी',
    trustDescription: 'सत्यापित चालक और सुरक्षित समुदाय।',
    cancelRide: 'सवारी रद्द करें',
    cancelBooking: 'मेरी बुकिंग रद्द करें',
    selectSeat: 'सीट चुनें',
    chat: 'चैट',
    myRide: 'मेरी सवारी',
    groupChat: 'ग्रुप चैट',
    ridesLabel: 'सवारी',
    bookingTotal: 'कुल बुकिंग',
    seatsLabel: 'सीटें',
    seatLabel: 'सीट(स)',
    paymentLabel: 'भुगतान',
    cashLabel: 'नकद',
    passengers: 'यात्री',
    driver: 'चालक',
    seatsLeft: '{count} सीटें शेष',
    journeyComfort: 'यात्रा का आराम',
    journeyItinerary: 'यात्रा का विवरण',
    yourFare: 'आपका किराया',
    perSeatNote: 'प्रति सीट · कोई छुपा हुआ शुल्क नहीं',
    smokeFree: 'धूम्रपान रहित सवारी',
    petsWelcome: 'पालतू जानवरों का स्वागत है',
    luggageOk: 'सामान की अनुमति है',
    ladiesOnly: 'केवल महिलाएं',
    approvalRequired: 'अनुमोदन आवश्यक',
    instantBooking: 'त्वरित बुकिंग',
    vibes: 'वाइब्स',
    date: 'तारीख',
    time: 'समय',
    duration: 'अवधि',
    seatsLeftLabel: 'सीटें शेष',
    assignedVehicle: 'सौपा गया वाहन',
    compactSedan: 'कॉम्पैक्ट सेडान',
    premiumSuv: 'प्रीमियम एसयूवी',
    swiftBike: 'स्विफ्ट बाइक',
    standardVehicle: 'मानक',
  },
  cancelRide: {
    title: 'सवारी रद्द करें',
    subtitle: 'कृपया रद्द करने का कारण चुनें',
    reasonDriverFar: 'चालक बहुत दूर है',
    reasonChangedMind: 'मेरा इरादा बदल गया',
    reasonCheaperRide: 'सस्ती सवारी मिली',
    reasonWaitLong: 'प्रतीक्षा समय बहुत लंबा है',
    reasonPlansChanged: 'योजनाएं बदल गईं',
    reasonAlternative: 'दूसरी सवारी मिल गई',
    reasonUncomfortable: 'पिकअप बिंदु के साथ सहज नहीं',
    reasonNotAvailable: 'वाहन उपलब्ध नहीं है',
    reasonOther: 'अन्य',
    successMessage: 'रद्द करना सफल रहा।',
    errorMessage: 'रद्द करना विफल रहा।',
    confirmCancel: 'रद्द करने की पुष्टि करें',
    keepRide: 'सवारी रखें',
    otherReasonPlaceholder: 'कृपया कारण बताएं...',
  },
  locationSelection: {
    titlePrefix: 'कहाँ',
    titleHighlight: 'जाना',
    titleSuffix: 'है?',
    subtitle: 'अपनी यात्रा शुरू करने के लिए स्थान चुनें।',
    startLabel: 'कहाँ से?',
    startPlaceholder: 'पिकअप स्थान खोजें...',
    destinationLabel: 'कहाँ तक?',
    destinationPlaceholder: 'गंतव्य स्थान खोजें...',
    continueJourney: 'यात्रा जारी रखें',
    contextualInfo: 'सत्यापित भागीदारों के साथ सवारी करें।',
  },
  mapPicker: {
    title: 'स्थान चुनें',
    searchPlaceholder: 'स्थान खोजें...',
    setPickup: 'पिकअप सेट करें',
    setDestination: 'गंतव्य सेट करें',
    setStop: 'स्टॉप सेट करें',
    selectedArea: 'चयनित क्षेत्र',
    selectLocation: 'स्थान चुनें',
    recentSearches: 'हाल की खोजें',
  },
  routeSelection: {
    headerTitle: 'मार्ग चुनें',
    stepIndicator: 'चरण 1/6',
    title: 'सर्वोत्तम मार्ग चुनें',
    subtitle: 'वह मार्ग चुनें जो आपके लिए सबसे उपयुक्त हो।',
    recommended: 'अनुशंसित',
    trustBadge: 'वर्डेंट ट्रस्ट सत्यापित',
    continue: 'जारी रखें',
  },
  middleStops: {
    headerTitle: 'मध्य स्टॉप',
    stepIndicator: 'चरण 2/6',
    title: 'स्टॉप जोड़ें',
    subtitle: 'यात्रा के दौरान पिकअप या ड्रॉप-ऑफ स्टॉप जोड़ें।',
    startPointLabel: 'प्रारंभ बिंदु',
    stopLabel: 'स्टॉप',
    addMiddleStop: 'स्टॉप जोड़ें',
    addMiddleStopSub: 'मार्ग के साथ स्थान चुनें',
    destinationLabel: 'गंतव्य',
    optimizedRoute: 'अनुकूलित मार्ग',
    continue: 'जारी रखें',
  },
  middleStopMap: {
    headerTitle: 'स्टॉप जोड़ें',
    stepIndicator: 'चरण 2/6',
    searchPlaceholder: 'स्टॉप स्थान खोजें...',
    whereWillYouStop: 'आप कहाँ रुकेंगे?',
    addingStopsIncreasesInfo: 'स्टॉप जोड़ने से अधिक यात्रियों को मिलने की संभावना बढ़ जाती है।',
    suggestedStoppages: 'सुझाए गए स्टॉप',
    popular: 'लोकप्रिय',
    quickExit: 'त्वरित निकास',
    recentHistory: 'हाल का इतिहास',
    currentRoute: 'वर्तमान मार्ग',
    selectedStop: 'चयनित स्टॉप',
    addedStops: 'जोड़े गए स्टॉप',
    continue: 'जारी रखें',
  },
  dateSelection: {
    headerTitle: 'तारीख चुनें',
    stepIndicator: 'चरण 3/6',
    title: 'यात्रा की तारीख',
    subtitle: 'आप कब यात्रा करने की योजना बना रहे हैं?',
    currentLabel: 'वर्तमान',
    daysOfWeek: ['रवि', 'सोम', 'मंगल', 'बुध', 'गुरु', 'शुक्र', 'शनि'],
    selectedDate: 'चयनित तारीख',
    noneSelected: 'कोई नहीं',
    next: 'अगला',
  },
  timeSelection: {
    headerTitle: 'समय चुनें',
    stepIndicator: 'चरण 4/6',
    title: 'रवाना होने का',
    titleHighlight: 'समय',
    subtitle: 'सटीक पिकअप के लिए प्रस्थान समय निर्धारित करें।',
    selectedTimeLabel: 'चयनित समय',
    formatLabel: 'समय प्रारूप',
    arrivalNote: 'यातायात के आधार पर आगमन समय भिन्न हो सकता है।',
    continue: 'जारी रखें',
  },
  seatSelection: {
    headerTitle: 'सीटें चुनें',
    title: 'सीटों की संख्या',
    subtitle: 'कितनी सीटें उपलब्ध हैं?',
    seatSelected: 'सीट चुनी गई',
    seatsSelected: 'सीटें चुनी गईं',
    selectVehicleFirst: 'सीटिंग व्यवस्था देखने के लिए कृपया एक वाहन चुनें।',
    yourVehicles: 'आपके वाहन',
    fiveSeater: '5 सीटर',
    sevenSeater: '7 सीटर',
    driverLabel: 'चालक',
    legendSelected: 'चयनित',
    legendAvailable: 'उपलब्ध',
    legendOccupied: 'भरी हुई',
    seatsOffering: 'उपलब्ध सीटें',
    estEarnings: 'अनुमानित कमाई',
    continue: 'जारी रखें',
  },
  priceSelection: {
    headerTitle: 'मूल्य निर्धारण',
    title: 'मूल्य सेट करें',
    subtitle: 'प्रति सीट किराया निर्धारित करें।',
    basePriceLabel: 'मूल किराया',
    recommendedBadge: 'अनुशंसित',
    frontSeatPremiumTitle: 'फ्रंट सीट प्रीमियम',
    frontSeatPremiumDesc: 'फ्रंट सीट के लिए अतिरिक्त शुल्क',
    premiumAmountLabel: 'प्रीमियम राशि',
    maxLimitNote: 'अधिकतम सीमा लागू है',
    multiStopTitle: 'मल्टी-स्टॉप मूल्य निर्धारण',
    multiStopSubtitle: 'विभिन्न स्टॉप के लिए कीमतें अनुकूलित करें',
    customizePricing: 'मूल्य अनुकूलित करें',
    continueButton: 'जारी रखें',
    segmentSheetTitle: 'खंड मूल्य निर्धारण',
    segmentSheetSubtitle: 'प्रत्येक स्टॉप के लिए कीमतें सेट करें',
    segmentLabel: 'खंड',
    minPriceLabel: 'न्यूनतम',
    maxPriceLabel: 'अधिकतम',
    cancelButton: 'रद्द करें',
    saveButton: 'सहेजें',
    frontSeatProjectedLabel: 'फ्रंट सीट अनुमानित',
    perSeatPrice: 'प्रति सीट मूल्य',
    basePlusPremium: 'इस लेग के लिए बेस + {percentage}% प्रीमियम की गणना की गई',
  },
  requestType: {
    headerTitle: 'अनुरोध का प्रकार',
    title: 'बुकिंग का प्रकार चुनें',
    subtitle: 'यात्री आपकी सवारी को कैसे बुक कर सकते हैं?',
    instantBookingTitle: 'त्वरित बुकिंग',
    instantBookingSubtitle: 'अनुरोधों को स्वचालित रूप से स्वीकार करें',
    requestReviewTitle: 'समीक्षा का अनुरोध करें',
    requestReviewSubtitle: 'प्रत्येक अनुरोध को मैन्युअल रूप से स्वीकार करें',
    proTipTitle: 'प्रो टिप',
    proTipText: 'त्वरित बुकिंग से आपकी सवारी जल्दी भरने की संभावना बढ़ जाती है।',
    continueButton: 'जारी रखें',
  },
  summaryPublish: {
    headerTitle: 'सारांश',
    title: 'सवारी प्रकाशित करें',
    subtitle: 'प्रकाशन से पहले अपने सवारी विवरण की समीक्षा करें।',
    departureLabel: 'प्रस्थान',
    arrivalLabel: 'आगमन',
    vehicleLabel: 'वाहन',
    availabilityLabel: 'उपलब्धता',
    ridePreferencesLabel: 'सवारी प्राथमिकताएं',
    noSmoking: 'धूम्रपान निषेध',
    petsAllowed: 'पालतू जानवरों की अनुमति',
    chillMusic: 'रिलैक्स संगीत',
    publishRideButton: 'सवारी प्रकाशित करें',
    termsText1: 'प्रकाशित करके, आप हमारी ',
    termsLink: 'सामुदायिक दिशानिर्देशों',
    termsText2: ' और सुरक्षा शर्तों से सहमत होते हैं।',
    routeSummaryLabel: 'मार्ग सारांश',
    departureScheduleLabel: 'प्रस्थान अनुसूची',
    addVehicleLabel: 'वाहन जोड़ें',
    addPreferencesLabel: 'प्राथमिकताएं जोड़ें',
  },
  publishSuccess: {
    headerTitle: 'सफलता',
    title: 'सवारी प्रकाशित हुई!',
    subtitle: 'आपकी सवारी अब यात्रियों के लिए उपलब्ध है।',
    infoTitle: 'अगले कदम',
    infoText: 'यात्रियों के बुकिंग अनुरोधों पर नज़र रखें और उनके साथ चैट करें।',
    primaryCTA: 'मेरी सवारी पर जाएं',
    secondaryCTA: 'विवरण साझा करें',
  },
  bookRideInfo: {
    heroTitle: 'सवारी खोजें',
    heroSubtitle: 'सत्यापित समुदाय भागीदारों के साथ यात्रा करें।',
    pickupLabel: 'पिकअप',
    pickupPlaceholder: 'पिकअप स्थान दर्ज करें',
    destinationLabel: 'गंतव्य',
    destinationPlaceholder: 'गंतव्य स्थान दर्ज करें',
    travelDateLabel: 'यात्रा की तारीख',
    datePlaceholder: 'आज',
    peopleCountLabel: 'यात्रियों की संख्या',
    peopleCountSub: 'आपके साथ कितने लोग हैं?',
    searchButton: 'सवारी खोजें',
    recentSearchesTitle: 'हाल की खोजें',
    clearAll: 'सभी साफ करें',
    trustTitle: 'वर्डेंट ट्रस्ट',
    trustDescription: 'सुरक्षित और विश्वसनीय यात्रा का अनुभव।',
    brandName: 'राइड पूल कंपनी',
    local: 'स्थानीय',
    intercity: 'इंटरसिटी',
    localServiceArea: 'स्थानीय सेवा क्षेत्र',
    requestLocalPartner: 'स्थानीय पार्टनर का अनुरोध करें',
  },
  availableRides: {
    heroTitle: 'उपलब्ध सवारी',
    heroSubtitle: 'अपनी यात्रा के लिए सर्वोत्तम विकल्प चुनें।',
    timeFilterLabel: 'समय',
    noSmokingFilterLabel: 'धूम्रपान निषेध',
    ladiesOnlyFilterLabel: 'केवल महिलाएं',
    topRatedFilterLabel: 'टॉप रेटेड',
    frequentCoRiderBadge: 'बार-बार आने वाले यात्री',
    perSeatLabel: 'प्रति सीट',
    seatsLeftLabel: 'सीटें शेष',
    bookButton: 'बुक करें',
    detailsButton: 'विवरण',
    stopLabel: 'स्टॉप',
    searchSummaryDate: 'तारीख',
    searchSummarySeats: 'सीटें',
  },
  rideFilters: {
    title: 'फिल्टर',
    proximityTitle: 'निकटता',
    nearPickup: 'पिकअप के पास',
    nearDropoff: 'ड्रॉप-ऑफ के पास',
    departureTimeTitle: 'प्रस्थान का समय',
    preferencesTitle: 'प्राथमिकताएं',
    seatAvailabilityTitle: 'सीट की उपलब्धता',
    seatsRequiredLabel: 'आवश्यक सीटें',
    applyFilters: 'फिल्टर लागू करें',
    clearAll: 'सभी साफ करें',
  },
  rideInformation: {
    title: 'सवारी की जानकारी',
    distanceRemaining: 'दूरी शेष',
    driverInfoTitle: 'चालक की जानकारी',
    carInfoTitle: 'कार की जानकारी',
    timelineTitle: 'समयरेखा',
    rulesTitle: 'नियम',
    amenitiesTitle: 'सुविधाएं',
    fareDetailsTitle: 'किराये का विवरण',
    seatFareLabel: 'सीट का किराया',
    serviceFeeLabel: 'सेवा शुल्क',
    sustainabilityFeeLabel: 'स्थिरता शुल्क',
    bookSeatButton: 'सीट बुक करें',
    guidelinesNote: 'सवारी के दौरान कृपया दिशानिर्देशों का पालन करें।',
    noSmoking: 'धूम्रपान निषेध',
    petsAllowed: 'पालतू जानवरों की अनुमति',
    freeWifi: 'मुफ्त वाई-फाई',
    usbCharging: 'USB चार्जिंग',
    fellowTravelers: 'साथी यात्री',
    journeyComfort: 'यात्रा का आराम',
    seatsOpen: 'सीटें खाली',
    departure: 'प्रस्थान',
    journey: 'यात्रा',
    seatsLeft: 'सीटें शेष',
  },
  selectSeat: {
    title: 'सीट चुनें',
    subtitle: 'अपनी पसंद की सीट चुनें।',
    headerTitle: 'सीट चयन',
    driverLabel: 'चालक',
    verifiedVehicle: 'सत्यापित वाहन',
    arrivingIn: 'आगमन में समय',
    estimatedFare: 'अनुमानित किराया',
    legendAvailable: 'उपलब्ध',
    legendSelected: 'चयनित',
    legendBooked: 'बुक की गई',
    legendOccupied: 'भरी हुई',
    selectVehicleFirst: 'सीटिंग व्यवस्था देखने के लिए कृपया एक वाहन चुनें।',
    yourVehicles: 'आपके वाहन',
    summaryTitle: 'सारांश',
    seatSelected: 'सीट चयनित',
    totalPayable: 'कुल देय',
    continue: 'जारी रखें',
    holdTimerNote: 'आपकी सीट 5 मिनट के लिए होल्ड पर है।',
    seatsSelected: '',
    pickSeatToContinue: '',
    bookMySeat: ''
  },
  bookingConfirmed: {
    successTitle: 'बुकिंग सफल!',
    successSubtitle: 'आपकी सवारी की पुष्टि हो गई है।',
    driverLabel: 'चालक',
    verifiedLabel: 'सत्यापित',
    pickupTimeLabel: 'पिकअप समय',
    arrivingIn: '{min} मिनट में पहुंच रहे हैं',
    seatNumberLabel: 'सीट नंबर',
    windowPreference: 'खिड़की की सीट पसंद की गई',
    safetyGuardTitle: 'सुरक्षा गार्ड सक्रिय',
    safetyGuardSubtitle: 'आपकी यात्रा को GPS द्वारा ट्रैक किया जा रहा है।',
    primaryCTA: 'मेरी सवारी पर जाएं',
    secondaryCTA: 'यात्रा विवरण साझा करें',
    plateLabel: 'प्लेट',
  },
  settings: {
    headerTitle: 'सेटिंग्स',
    appName: 'राइडपूलकंपनी',
    notifications: 'सूचनाएं',
    pushNotifications: 'पुश सूचनाएं',
    pushNotificationsDesc: 'सवारी अपडेट के लिए सक्षम करें',
    appearance: 'दिखावट',
    theme: 'थीम',
    lightMode: 'वर्तमान: लाइट मोड',
    darkMode: 'वर्तमान: डार्क मोड',
    darkModeToggle: 'डार्क मोड',
    preferences: 'प्राथमिकताएं',
    language: 'भाषा',
    languageEn: 'English',
    languageHi: 'हिंदी',
    region: 'क्षेत्र',
    emailSettings: 'ईमेल सूचनाएं',
    promotions: 'प्रचार',
    rideReceipts: 'सवारी रसीदें',
    accountSecurity: 'खाते की सुरक्षा',
    logout: 'लॉगआउट',
    logoutConfirmTitle: 'लॉगआउट',
    logoutConfirmMessage: 'क्या आप वाकई लॉगआउट करना चाहते हैं? आपको अपने खाते तक पहुँचने के लिए फिर से लॉग इन करना होगा।',
    logoutConfirmButton: 'लॉगआउट',
    logoutConfirmCancel: 'लॉग इन रहें',
    version: 'ऐप संस्करण 4.12.0-वर्डेंट',
  },
  myRides: {
    headerTitle: 'मेरी सवारी',
    upcomingTab: 'आगामी',
    draftsTab: 'ड्राफ्ट',
    completedTab: 'पूरा हुआ',
    archiveTab: 'संग्रह',
    newRequestsTitle: 'नए अनुरोध',
    pendingBadge: '{count} लंबित',
    publishedRidesTitle: 'आपकी सवारी',
    draftsTitle: 'ड्राफ्ट',
    clearAll: 'सभी साफ करें',
    completedTitle: 'हाल ही में पूरा हुआ',
    requestsTab: 'अनुरोध',
    noUpcomingTitle: 'कोई आगामी सवारी नहीं',
    noUpcomingDesc: 'आपके द्वारा प्रकाशित सवारी यहां दिखाई देगी',
    noRequestsTitle: 'कोई नया अनुरोध नहीं',
    noRequestsDesc: 'आपकी सवारी के लिए अनुरोध यहां दिखाई देंगे',
    noDraftsTitle: 'अभी तक कोई ड्राफ्ट नहीं',
    noDraftsDesc: 'आपकी सहेजी गई सवारी यहां दिखाई देगी',
    noCompletedTitle: 'कोई पूरी हुई सवारी नहीं',
    noCompletedDesc: 'पुरानी सवारी यहां दिखाई देगी',
    noArchiveTitle: 'कोई संग्रह सवारी नहीं',
    noArchiveDesc: 'पुरानी और रद्द की गई सवारी यहां दिखाई देगी',
    cancelRideAlertTitle: 'सवारी रद्द करें',
    cancelRideAlertMsg: 'क्या आप वाकई इस प्रकाशित सवारी को रद्द करना चाहते हैं?',
    cancelRideConfirm: 'सवारी रद्द करें',
    cancelRideKeep: 'सवारी रखें',
    cancelRideError: 'सवारी रद्द करने में विफल।',
    deleteDraftAlertTitle: 'ड्राफ्ट हटाएं',
    deleteDraftAlertMsg: 'क्या आप वाकई इस ड्राफ्ट को हटाना चाहते हैं?',
    deleteDraftConfirm: 'हटाएं',
    deleteDraftCancel: 'रद्द करें',
    clearDraftsAlertTitle: 'सभी ड्राफ्ट साफ करें',
    clearDraftsAlertMsg: 'इससे आपके सभी सहेजे गए सवारी ड्राफ्ट हट जाएंगे।',
    clearDraftsConfirm: 'सभी साफ करें',
    clearDraftsCancel: 'रद्द करें',
    startsIn: 'शुरू होता है',
    started: 'शुरू हो गया',
    mins: 'मि',
    hours: 'घं',
    completedStatus: 'पूरा हुआ',
    requestPending: 'अनुरोध लंबित',
    rideConfirmed: 'सवारी की पुष्टि की गई',
    confirmedStatus: 'पुष्टि की गई',
    pendingStatus: 'लंबित',
    youAreDriver: 'आप चालक हैं',
    yourVehicle: 'आपका वाहन',
    vehicleDetails: 'वाहन विवरण',
  },
  userProfileDetail: {
    headerTitle: 'राइडकनेक्ट',
    verifiedMember: 'सत्यापित सदस्य',
    preferences: 'वरीयताएँ',
    vehicleInfo: 'वाहन की जानकारी',
    viewRatings: '{{count}} रेटिंग का विवरण देखें',
    recentReviews: 'हाल की समीक्षाएं',
    reportUser: '{{name}} की रिपोर्ट करें',
  },
  developer: {
    networkLogsTitle: 'नेटवर्क लॉग्स',
    noLogsTitle: 'कोई नेटवर्क लॉग नहीं',
    noLogsDesc: 'एपीआई कॉल करें ताकि वे यहाँ दिखाई दें।',
    clear: 'साफ़ करें',
    close: 'बंद करें',
    requestDetails: 'अनुरोध विवरण',
    overview: 'अवलोकन',
    requestHeaders: 'अनुरोध हेडर्स',
    requestBody: 'अनुरोध बॉडी',
    responseHeaders: 'प्रतिक्रिया हेडर्स',
    responseBody: 'प्रतिक्रिया बॉडी',
    pending: 'लंबित',
    noBody: 'कोई बॉडी नहीं',
    noHeaders: 'कोई हेडर्स नहीं',
  },
};
