import { Translations } from './types';

export const hi: Translations = {
  login: {
    brandName: 'द डिजिटल क्यूरेटर',
    brandTagline: 'अपने डिजिटल अभयारण्य में कदम रखें।',
    phoneLabel: 'फ़ोन नंबर',
    phonePlaceholder: '+91 98765 43210',
    phoneError: 'कृपया एक वैध फ़ोन नंबर दर्ज करें',
    getOtp: 'OTP प्राप्त करें',
    otpInfoBox: 'आपके खाते को सुरक्षित रूप से सत्यापित करने के लिए हम 6-अंकीय कोड भेजेंगे।',
    noAccount: 'खाता नहीं है?',
    signUp: 'साइन अप करें',
    orContinueWith: 'या इसके साथ जारी रखें',
  },
  otpVerification: {
    titlePrefix: 'पुष्टि करें कि यह',
    titleHighlight: 'आप',
    subtitle: 'हमने आपके पंजीकृत मोबाइल नंबर पर 6 अंकों का सत्यापन कोड भेजा है:',
    verifyButton: 'पहचान सत्यापित करें',
    verifyingButton: 'सत्यापित किया जा रहा है...',
    didNotReceive: 'कोड प्राप्त नहीं हुआ?',
    resendNow: 'अभी कोड फिर से भेजें',
    resendIn: 'में कोड फिर से भेजें',
    secureAuth: 'सुरक्षित सत्यापन',
    needHelp: 'मदद चाहिए? सारा से चैट करें',
    privacyPolicy: 'गोपनीयता नीति',
    supportCenter: 'सहायता केंद्र',
  },
  profileSetup: {
    headerTitle: 'वरदंत ट्रस्ट',
    heroTitle: 'घर वापसी पर स्वागत है।',
    heroSubtitle: 'आइए आपके अनुभव को बेहतर बनाने के लिए आपकी डिजिटल पहचान को व्यवस्थित करें।',
    dobRequiredError: 'आगे बढ़ने के लिए कृपया अपनी कानूनी जन्म तिथि प्रदान करें।',
    identityProfile: 'पहचान प्रोफ़ाइल',
    publicPresence: 'सार्वजनिक उपस्थिति',
    fullNameLabel: 'पूरा नाम',
    fullNamePlaceholder: 'उदा. जूलियन रीड',
    dobLabel: 'जन्म तिथि',
    genderLabel: 'लिंग',
    genderFemale: 'महिला',
    genderMale: 'पुरुष',
    genderOther: 'अन्य',
    locationPreference: 'स्थान वरीयता',
    locationPlaceholder: 'अपना शहर खोजें...',
    nearbyOnly: 'केवल पास के',
    globalReach: 'वैश्विक पहुंच',
    newsletter: 'न्यूज़लेटर',
    curatedPicks: 'क्यूरेटेड पिक्स',
    contentPreferences: 'सामग्री प्राथमिकताएं',
    interestDigitalArt: 'डिजिटल आर्ट',
    interestSustainableLiving: 'सतत जीवन',
    interestMinimalism: 'न्यूनतमवाद',
    interestTypography: 'टाइपोग्राफी',
    interestTechEthics: 'टेक एथिक्स',
    interestArchitecture: 'आर्किटेक्चर',
    almostThere: 'लगभग वहां!',
    identityVerified: 'आपके मुख्य पहचान विवरण सत्यापित और सुरक्षित हैं।',
    completeSetup: 'सेटअप पूरा करें',
    footerVersion: 'सुरक्षित संपादकीय वातावरण • v1.0.2',
  },
  profileHub: {
    headerTitle: 'प्रोफ़ाइल',
    identityVerified: 'पहचान सत्यापित',
    proPooler: 'प्रो पूलर',
    rating: 'रेटिंग',
    rides: 'सवारियां',
    memberSince: 'सदस्यता की शुरुआत',
    trustScore: 'विश्वास स्कोर',
    trustScoreDescr: 'आपकी निरंतरता समुदाय को सभी के लिए सुरक्षित और अधिक विश्वसनीय बनाती है।',
    accountManagement: 'खाता प्रबंधन',
    supportLegal: 'सहायता और कानूनी',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    editProfileDescr: 'नाम, बायो और संपर्क विवरण',
    identityVerification: 'पहचान सत्यापन',
    identityVerificationDescr: 'आधार और वाहन दस्तावेज़',
    travelPreferences: 'यात्रा प्राथमिकताएं',
    travelPreferencesDescr: 'संगीत, धूम्रपान और पालतू जानवरों के विकल्प',
    paymentMethods: 'भुगतान के तरीके',
    paymentMethodsDescr: 'वॉलेट, कार्ड और UPI',
    ratingsReviews: 'रेटिंग और समीक्षाएं',
    ratingsReviewsDescr: 'देखें कि दूसरे क्या कह रहे हैं',
    changePassword: 'पासवर्ड बदलें',
    changePasswordDescr: 'सुरक्षा और प्रमाणीकरण',
    helpSupport: 'सहायता और समर्थन',
    aboutUs: 'हमारे बारे में',
    termsPrivacy: 'शर्तें और गोपनीयता',
    logout: 'लॉगआउट',
    deleteAccount: 'खाता हटाएं',
    navBook: 'बुक करें',
    navPublish: 'प्रकाशित करें',
    navMyRides: 'मेरी सवारी',
    navChats: 'चैट',
    navProfile: 'प्रोफ़ाइल',
  },
  editProfile: {
    headerTitle: 'प्रोफ़ाइल',
    successMessage: 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
    updatePhoto: 'प्रोफ़ाइल फ़ोटो अपडेट करें',
    fullNameLabel: 'पूरा नाम',
    fullNamePlaceholder: 'जैसे: जूलिएन रीड',
    emailLabel: 'ईमेल पता',
    emailPlaceholder: 'जैसे: julianne@sharmyride.com',
    phoneLabel: 'फ़ोन नंबर',
    phonePlaceholder: '+1 (555) 000-0000',
    dobLabel: 'जन्म तिथि',
    genderLabel: 'लिंग',
    bioLabel: 'संक्षिप्त विवरण',
    bioPlaceholder: 'प्रो पूलर • डाउनटाउन और सिलिकॉन वैली के बीच निरंतर यात्री...',
    cancel: 'रद्द करें',
    saveChanges: 'बदलाव सुरक्षित करें',
    fullNameRequired: 'पूरा नाम अनिवार्य है',
    fullNameMin: 'नाम कम से कम 3 अक्षरों का होना चाहिए',
    emailRequired: 'ईमेल पता अनिवार्य है',
    emailInvalid: 'कृपया एक मान्य ईमेल पता दर्ज करें',
    phoneRequired: 'फ़ोन नंबर अनिवार्य है',
    phoneInvalid: 'कृपया एक मान्य फ़ोन नंबर दर्ज करें',
    dobRequired: 'जन्म तिथि अनिवार्य है',
    genderRequired: 'कृपया अपना लिंग चुनें',
    bioMax: 'विवरण 200 अक्षरों से अधिक नहीं हो सकता',
  },
  dummyContent: {
    aboutTitle: 'हमारी कहानी',
    aboutBody: 'ShareMyRide सिर्फ एक कारपूलिंग ऐप नहीं है। हम एक "काइनेटिक सैंक्चुअरी" हैं—एक पेशेवर समुदाय जो समय, विश्वसनीयता और सामाजिक जुड़ाव को महत्व देता है। 2024 में स्थापित, हमारा मिशन हर यात्रा को जुड़ाव और साझा उत्पादकता की एक उद्देश्यपूर्ण यात्रा में बदलना है।',
    helpTitle: 'सहायता चाहिए?',
    helpBody: 'चाहे आप पिकअप पॉइंट पर फंसे हों या कोई तकनीकी समस्या हो, हमारी 24/7 सहायता टीम यहाँ है। हमारे सामुदायिक मंच से जुड़ें या अपनी सभी शंकाओं के त्वरित समाधान के लिए हमारी एआई सहायक "सारा" से चैट करें।',
    termsTitle: 'उपयोगकर्ता समझौता',
    termsBody: 'ShareMyRide का उपयोग करके, आप हमारे सामुदायिक सुरक्षा मानकों का सम्मान करने के लिए सहमत होते हैं। इसमें समय की पाबंदी, वाहन की स्वच्छता बनाए रखना और आधार और ड्राइविंग क्रेडेंशियल के माध्यम से अपनी पहचान सत्यापित करना शामिल है।',
  },
  travelPreferences: {
    headerTitle: 'यात्रा प्राथमिकताएं',
    heroTitle: 'आपका सफर,\nआपके नियम।',
    heroSubtitle: 'अपनी यात्रा को व्यक्तिगत बनाएं',
    nonSmoking: 'धूम्रपान मुक्त यात्रा',
    nonSmokingDescr: 'बिना धुएं की गंध वाले वाहनों को प्राथमिकता दें',
    womenOnly: 'केवल महिलाओं के लिए यात्रा',
    womenOnlyDescr: 'केवल महिला ड्राइवरों/पूलर्स के साथ मिलान करें',
    musicPreference: 'संगीत की पसंद',
    bollywood: 'बॉलीवुड',
    pop: 'पॉप',
    jazz: 'जैज़',
    podcast: 'पॉडकास्ट',
    silence: 'शांति',
    luggageAllowed: 'सामान की अनुमति',
    petFriendly: 'पालतू जानवरों के अनुकूल',
    savePreferences: 'प्राथमिकताएं सहेजें',
    enabled: 'सक्षम',
    disabled: 'अक्षम',
  },
  vehicleDetails: {
    headerTitle: 'वाहन विवरण',
    heroTitle: 'अपने वाहन को पंजीकृत करें',
    heroSubtitle: 'दूसरों को आपकी सवारी पहचानने में मदद करें',
    basicIdentity: 'बुनियादी पहचान',
    vehicleCompany: 'वाहन कंपनी',
    companyPlaceholder: 'जैसे- टेस्ला',
    carModel: 'कार मॉडल',
    modelPlaceholder: 'जैसे- मॉडल 3',
    technicalSpecs: 'तकनीकी विवरण',
    numberPlate: 'नंबर प्लेट',
    platePlaceholder: 'ABC-1234',
    vehicleType: 'वाहन का प्रकार',
    appearance: 'दिखावट',
    manufacturingYear: 'निर्माण वर्ष',
    color: 'रंग',
    colorPlaceholder: 'पन्ना हरा',
    saveVehicle: 'वाहन सहेजें',
    successMessage: 'वाहन सफलतापूर्वक पंजीकृत किया गया!',
    bike: 'बाइक',
    hatchback: 'हैचबैक',
    suv: 'एसयूवी',
    sedan: 'सेडान',
  },
  chat: {
    headerTitle: 'संदेश',
    searchPlaceholder: 'बातचीत खोजें...',
    recentMessages: 'हाल के संदेश',
    noMessages: 'अभी तक कोई संदेश नहीं',
    newMessage: 'नया संदेश',
    rideLabel: 'सवारी:',
    yesterday: 'कल',
    activeDrivers: 'सक्रिय चालक',
  },
  rideDetails: {
    headerTitle: 'मेरी सवारी',
    liveTracking: 'लाइव ट्रैकिंग',
    pickupLabel: 'पिकअप',
    stopLabel: 'स्टॉप {count}',
    destinationLabel: 'गंतव्य',
    estimatedArrival: 'अनुमानित आगमन',
    minsAway: '{count} मिनट दूर',
    totalFare: 'कुल किराया',
    verified: 'सत्यापित',
    otherRiders: 'अन्य यात्री',
    spotsLeft: '{count} सीटें शेष',
    coRider: 'सह-यात्री',
    joiningAt: '{stop} पर जुड़ रहे हैं',
    trustTitle: 'वरदंत ट्रस्ट सुरक्षा',
    trustDescription: 'आपकी सवारी हमारे व्यापक सुरक्षा प्रोटोकॉल द्वारा कवर की गई है। रीयल-टाइम आपातकालीन शेयरिंग सक्रिय है।',
    cancelRide: 'सवारी रद्द करें',
    chat: 'चैट',
  },
  cancelRide: {
    title: 'सवारी रद्द करें?',
    subtitle: 'कृपया हमें बताएं कि आप सवारी क्यों रद्द कर रहे हैं। इससे हमें आपके सवारी अनुभव को बेहतर बनाने में मदद मिलेगी।',
    reasonDriverFar: 'ड्राइवर बहुत दूर है',
    reasonChangedMind: 'मेरा मन बदल गया',
    reasonCheaperRide: 'एक सस्ती सवारी मिल गई',
    reasonWaitLong: 'प्रतीक्षा का समय बहुत लंबा है',
    reasonOther: 'अन्य कारण',
    confirmCancel: 'रद्दीकरण की पुष्टि करें',
    keepRide: 'मेरी सवारी बनाए रखें',
    otherReasonPlaceholder: 'कृपया विवरण दें...',
  },
  locationSelection: {
    titlePrefix: 'हम कहाँ ',
    titleHighlight: 'जा रहे',
    titleSuffix: ' हैं?',
    subtitle: 'निर्देशांक चुनकर अपनी यात्रा शुरू करें।',
    startLabel: 'प्रस्थान बिंदु',
    startPlaceholder: 'पिक-अप स्थान...',
    destinationLabel: 'अंतिम गंतव्य',
    destinationPlaceholder: 'कहाँ जाना है?',
    continueJourney: 'यात्रा जारी रखें',
    contextualInfo: 'जब तक आप किसी भागीदार की पुष्टि नहीं करते तब तक आपका स्थान निजी रहता है। सर्वोत्तम मिलान के लिए सटीकता महत्वपूर्ण है।',
  },
};







